### ISSUE TITLE
电视台缺失

### ISSUE THREAD

**Issue by yingxiao6667** [fanmingming/live#100]
Global里面怎么没有中天新闻那些台湾电视台了呢？

**Comment by fanmingming** [comment]
感谢提问。有些失效的频道会更新去掉，找到新的源也会更新上来。请继续关注后面的更新。

**Comment by door-not** [comment]
最新更新的源 有点问题 看看电视就会黑屏加载 然后重新拨其他频道在播回来就正常了 一个小时之内可能出现一到俩次 就是最近更新出现的 也可能是我个人网络波动问题   但是之前的使用过程很少遇到过这种问题

**Comment by fanmingming** [comment]
之前整点之前观看一个频道持续到整点后会出现这样的问题，是源的构建问题，这个问题已经解决了。卡顿的情况应该是源本身请求量大或者是vercel的网络波动导致的。
