### ISSUE TITLE
cctv16-4k

### ISSUE THREAD

**Issue by yalicez** [fanmingming/live#106]
## 意见建议
请在此提出您的意见或建议。
感谢包头大神提供免费的直播源，包头移动宽带也可以看，而且明显比其他高清源画质好，咨询一下，sony电视系统看cctv16-4k就特别卡没法看，换成apple tv 看就没问题，有什么sony系统app不卡推荐的吗

**Comment by fanmingming** [comment]
我是在Fire TV使用，没用过sony电视。你可以试试Tivimate。如果是联通用户的话留一下邮箱，发你内蒙古联通单播源！

**Comment by Ritchie1108** [comment]
> 我是在Fire TV使用，没用过sony电视。你可以试试Tivimate。如果是联通用户的话留一下邮箱，发你内蒙古联通单播源！

我这边用的这个客户端 https://m3u-ip.tv/
ipv6plus的源里有几个台有画面但是没声音, 编码的问题?

**Comment by sandaisi** [comment]
> 我是在Fire TV使用，没用过sony电视。你可以试试Tivimate。如果是联通用户的话留一下邮箱，发你内蒙古联通单播源！

大佬能给我发一份联通源吗？谢谢，baidu163msn@gmail.com

**Comment by yalicez** [comment]
您的建议很好，使用了tivimate看4k就很流畅，而且速度很快，我的邮箱zj9357@163.com，谢谢。

**Comment by yalicez** [comment]
您的建议很好，使用了tivimate看4k就很流畅，而且速度很快，我的邮箱zj9357@163.com，谢谢。

**Comment by fanmingming** [comment]
> > 我是在Fire TV使用，没用过sony电视。你可以试试Tivimate。如果是联通用户的话留一下邮箱，发你内蒙古联通单播源！
> 
> 我这边用的这个客户端 https://m3u-ip.tv/ ipv6plus的源里有几个台有画面但是没声音, 编码的问题?

应该是播放器解码的问题。 最近比较忙，ipv6plus部分频道可能有失效的情况，不忙会修复更新。

**Comment by fanmingming** [comment]
@sandaisi @yalicez 邮件已发送，请查收。
