### ISSUE TITLE
浙江公共新闻能否将更新下源？

### ISSUE THREAD

**Issue by Lovest20018** [fanmingming/live#111]
## 遇到的问题	
浙江公共新闻老人家用播放一直个画面循环了

## 您使用的源
Global

## 有问题的频道名称
浙江公共新闻

**Comment by fanmingming** [comment]
感谢提出问题，浙江公共频道在亚运会期间因版权原因播放循环画面。- -！

**Comment by fanmingming** [comment]
😓 抱歉，已修复！
