### ISSUE TITLE
能单独做一个4K/8K节目单吗

### ISSUE THREAD

**Issue by kwong900** [fanmingming/live#112]
## 意见建议
请在此提出您的意见或建议。

**Comment by xibeilang0616** [comment]
不错的建议！
前一段时间友善的肥羊那边好像以前有个 CCTV1 4k频道，好像是HDR格式的，兼容市面上大部分的电视，那4K那色彩和清晰度是相当可以。最近好像失效了，失效，串台串到江苏卫视的标清频道去了。

肥羊的直播源维护性差，大部分的直播源放到那儿就不闻不问，等着自生自灭。

那个 CCTV1 4k频道，不像CCTV 4k、 CCTV16、欢乐剧场、纯享超清等频道是HLP格式的，色彩不准，画面灰蒙蒙的。

**Comment by kwong900** [comment]
因为现在都是大尺寸高刷屏电视，高清的直播源也差点意思，要求不高只希望央视那十几个台有4K直播源就好，方便看亚运会

**Comment by fanmingming** [comment]
抱歉啊，个人精力有限。😵‍💫
