### ISSUE TITLE
是否可以有维护更新的的邮件通知，第一时间获知直播源地址变动

### ISSUE THREAD

**Issue by zhanhongcheng** [fanmingming/live#113]
首先肯定的是持续维护的努力，值得赞赏。

其次，是否可以提供进一步的维护内容，例如开展付费订阅用户，付费订阅用户第一时间获得直播源的更新通知，方便换源。订阅用户可以PayPal付款或支付宝付款。

感谢公益，不给只依靠热情对项目发展肯定远远不够，路也走不长！

**Comment by fanmingming** [comment]
感谢对项目的肯定！项目会持续免费，不会搞收费或订阅。有提示画面的话，建议刷新源继续使用。遇到大部分失效的情况，耐心等待修复就好。

**Comment by zhanhongcheng** [comment]
嗯，收到。问下是否可以提供telegram的群交流支持？

**Comment by fanmingming** [comment]
抱歉，个人精力有限，暂时不会考虑建群。
