### ISSUE TITLE
CHC电影频道

### ISSUE THREAD

**Issue by caizi86** [fanmingming/live#114]
## 意见建议
请在此提出您的意见或建议。

本人小白，最近一直用您的直播源看电影，这次更新却找不到CHC的三个电影频道了。不知道何时能恢复呢？
还有就是希望下次更新时，可不可以把这三个CHC电影频道，排列到播放列表里CCTV中央台下边啊，每次找台要拉到最下边有点麻烦。
感谢——祝顺利。

**Comment by fanmingming** [comment]
感谢反馈，目前CHC系列三个频道暂时没有比较稳定的IPv4源，建议通过IPv6源来观看高画质的CHC频道。
