### ISSUE TITLE
DNS似乎很挑剔或者已经被污染？

### ISSUE THREAD

**Issue by klcb2010** [fanmingming/live#121]
很久以前  大概是9月初   WiFi和网线直连直播可以播放，高峰期会卡顿；现在 WiFi和网线直连，任何时候都放不了。测试了移动网络没问题，猜测是DNS问题，于是 WiFi下爬上梯子试了一下，完美播放 ........

**Comment by fanmingming** [comment]
感谢反馈，9月29日上午开始Vercel的DNS解析出现了问题，已经在当天下午更换了解析。目前尚不清楚哪些地区的访问存在问题？麻烦提供下使用的运营商和所在地区。

**Comment by klcb2010** [comment]
> 感谢反馈，9月29日上午开始Vercel的DNS解析出现了问题，已经在当天下午更换了解析。目前尚不清楚哪些地区的访问存在问题？麻烦提供下使用的运营商和所在地区。

贵阳电信 宽带网络。

**Comment by fanmingming** [comment]
> > 感谢反馈，9月29日上午开始Vercel的DNS解析出现了问题，已经在当天下午更换了解析。目前尚不清楚哪些地区的访问存在问题？麻烦提供下使用的运营商和所在地区。
> 
> 贵阳电信 宽带网络。

感谢！测试贵阳电信可正常解析，建议本地更换下其他DNS地址，比如114.114.114.114或其他公共DNS。这个问题是国庆期间国内防火墙加强了管控导致的，后面或许会有改善。

**Comment by klcb2010** [comment]
> > > 感谢反馈，9月29日上午开始Vercel的DNS解析出现了问题，已经在当天下午更换了解析。目前尚不清楚哪些地区的访问存在问题？麻烦提供下使用的运营商和所在地区。
> > 
> > 
> > 贵阳电信 宽带网络。
> 
> 感谢！测试贵阳电信可正常解析，建议本地更换下其他DNS地址，比如114.114.114.114或其他公共DNS。这个问题是国庆期间国内防火墙加强了管控导致的，后面或许会有改善。

用了魔法 目前没问题了
