### ISSUE TITLE
global里面没有凤凰几个频道吗？

### ISSUE THREAD

**Issue by Lovest20018** [fanmingming/live#122]
## 意见建议

看到ipv6里面有。记得之前也有的。还有方便的话,是否能调整下省内频道跟国际的顺序？

**Comment by fanmingming** [comment]
感谢反馈，IPv4的凤凰频道暂时没有找到稳定流畅的节目源，有相关频道节目源的情况下会更新添加。关于您提到省内频道和国际的顺序能详细讲一下吗？

**Comment by Lovest20018** [comment]
感谢回复。省内频道更国际频道的顺序指的是现在浙江与内蒙的分类在国际更港澳下面。因为我平时都是复制样式-卫视 以及部分的省内频道还要加上移动的凤凰源到nas自建的http服务器上，给父母通过tivimate更新源看的，他们测试频道跟国际等部分宗教频道都是不看的，这样的分类有时候会复制错误，当然，这个是小事情，只是提了一嘴，按您的方便来。

**Comment by fanmingming** [comment]
感谢，后面更新会注意这个问题。现在的分组确实有些乱。
