### ISSUE TITLE
请问这个源如何在tvbox使用啊？

### ISSUE THREAD

**Issue by hezhongfeng** [fanmingming/live#123]
这个链接 `https://live.fanmingming.com/tv/m3u/global.m3u` 配置到tvbox上的数据源和直播源上都没有效果呢？
tvbox是下载的最新的https://github.com/o0HalfLife0o/TVBoxOSC

**Comment by fanmingming** [comment]
你好。使用M3U To txt工具。使用方法可参考demo链接。

**Comment by klcb2010** [comment]
用代码中的链接吧， https://github.com/fanmingming/live/blob/main/tv/m3u/global.m3u

**Comment by hezhongfeng** [comment]
感谢🙏

**Comment by linchiwei123** [comment]
@hezhongfeng 请问可以发下你的配置链接吗，我试了好久还是不行

**Comment by wahahaer** [comment]
楼主链接还能用吗
