### ISSUE TITLE
是否更新一个TV Logo 为英文或拼音路径的版本呢

### ISSUE THREAD

**Issue by mickeyyeung** [fanmingming/live#124]
## 遇到的问题	
在Apple TV上的iPlayTV中，似乎对于中文的（省卫视）的TV logo无法显示，似乎是因为是图标是包括中文路径的原因，能否考虑提供一个英文或拼音版本路径的版本呢？谢谢
## 您使用的源
Global

## 有问题的频道名称
中文logo名的频道

**Comment by fanmingming** [comment]
感谢反馈，不显示中文名称应该是播放器本身的bug，更改频道台标为英文名称路径的工作量比较大，且项目开源时间较久，更改后可能会影响到其他引用项目logo路径的正常显示。非常抱歉！

**Comment by oscar-c** [comment]
只要把链接里面的中文换成URL encoded版本，这样iPlayTV就能获取图标了
