### ISSUE TITLE
[2409:8087:2001:20:2800:0:df6e:eb24] 这种类型是IPv6地址吗？

### ISSUE THREAD

**Issue by zhajingwen** [fanmingming/live#125]
http://[2409:8087:2001:20:2800:0:df6e:eb24]:80/wh7f454c46tw3553140416_-2021535160/ott.mobaibox.com/PLTV/3/224/3221228527/index.m3u8

**Comment by EkkoG** [comment]
https://datatracker.ietf.org/doc/html/rfc2732

**Comment by xibeilang0616** [comment]
> http://[2409:8087:2001:20:2800:0:df6e:eb24]:80/wh7f454c46tw3553140416_-2021535160/ott.mobaibox.com/PLTV/3/224/3221228527/index.m3u8

对头，这就是IPv6地址，检查一下自己手机、电脑IP地址有没有跟这类似一长串的字母数字组合的，不会查，自己度娘。如果光是192.168.1.✘     192.168.0.✘类似这种的，就是纯IPV4地址，没有IPV6地址，光猫和路由器没有设置好。
如果有2409、2408、240e打头一长串，还有192.168.1.✘    ，这叫IP地址双栈协议。

**Comment by xibeilang0616** [comment]
对头，这就是IPv6地址，检查一下自己手机、电脑IP地址有没有跟这类似一长串的字母数字组合的，不会查，自己度娘。如果光是192.168.1.✘     192.168.0.✘类似这种的，就是纯IPV4地址，没有IPV6地址，光猫和路由器没有设置好，自己不会设置，让专业人士。如果光猫和路由器设备太老古董，不支持IPV6，请更换最新设备。
       
      如果发型有类似这样的2409、2408、240e打头一长串字母数字组合，后面还有192.168.1.✘    ，这叫IP地址双栈协议。支持IPV6的网站或服务器走IPV6通道，不支持的老网站，走IPV4通道。

       听明白了没有啊？

**Comment by xibeilang0616** [comment]
> http://[2409:8087:2001:20:2800:0:df6e:eb24]:80/wh7f454c46tw3553140416_-2021535160/ott.mobaibox.com/PLTV/3/224/3221228527/index.m3u8

对头，这就是IPv6地址，检查一下自己手机、电脑IP地址有没有跟这类似一长串的字母数字组合的，不会查，自己度娘。如果光是192.168.1.✘     192.168.0.✘类似这种的，就是纯IPV4地址，没有IPV6地址，光猫和路由器没有设置好，自己不会设置，让专业人士。如果光猫和路由器设备太老古董，不支持IPV6，请更换最新设备。
       
 如果发型有类似这样的2409、2408、240e打头一长串字母数字组合，后面还有192.168.1.✘    ，这叫IP地址双栈协议。支持IPV6的网站或服务器走IPV6通道，不支持的老网站，走IPV4通道。

 听明白了没有啊？

**Comment by zhajingwen** [comment]
> > http://[2409:8087:2001:20:2800:0:df6e:eb24]:80/wh7f454c46tw3553140416_-2021535160/ott.mobaibox.com/PLTV/3/224/3221228527/index.m3u8
> 
> 对头，这就是IPv6地址，检查一下自己手机、电脑IP地址有没有跟这类似一长串的字母数字组合的，不会查，自己度娘。如果光是192.168.1.✘ 192.168.0.✘类似这种的，就是纯IPV4地址，没有IPV6地址，光猫和路由器没有设置好，自己不会设置，让专业人士。如果光猫和路由器设备太老古董，不支持IPV6，请更换最新设备。
> 
> 如果发现有类似这样的2409、2408、240e打头一长串字母数字组合，后面还有192.168.1.✘ ，这叫IP地址双栈协议。支持IPV6的网站或服务器走IPV6通道，不支持的老网站，走IPV4通道。
> 
> 听明白了没有啊？

明白嘞，谢谢大佬
