### ISSUE TITLE
源更新后的问题

### ISSUE THREAD

**Issue by yalicez** [fanmingming/live#126]
## 遇到的问题	
在tivimate上使用，源更新后，通过设置中的节目更新无法使用，只能删除掉重新添加才能使用，这个正常吗

## 您使用的源
Global

## 有问题的频道名称
在此填写的频道名称。

**Comment by xibeilang0616** [comment]
推荐简单易用APP：DIYP影音

界面本土化，适合国内用户的遥控器操作习惯，比国外的洋软件，比如kodi、Tivimate等等众多IPTV播放器好用多了。

该软件为空壳APP，无内置信号源，需要手动填写fanmingming的直播源。


奉上本人保存的该软件包，阿里云盘最近分享规则变了，改用中国移动的和彩云云盘永久分享

https://caiyun.139.com/m/i?035CgisrZZwqg

提取码：DAPg

以下是该软件的截屏

Screenshot_2023-09-17-23-51-38-831_com player diyp2020

Screenshot_2023-09-17-23-50-21-296_com player diyp2020

Screenshot_2023-09-17-23-51-10-009_com player diyp2020

**Comment by fanmingming** [comment]
> ## 遇到的问题
> 在tivimate上使用，源更新后，通过设置中的节目更新无法使用，只能删除掉重新添加才能使用，这个正常吗
> 
> ## 您使用的源
> Global
> 
> ## 有问题的频道名称
> 在此填写的频道名称。

感谢提问，正版Tivimate版本4.7.0不存在更新后无法播放的情况。建议使用非破解版Tivimate来观看使用。

**Comment by beyondth** [comment]
> 推荐简单易用APP：DIYP影音
> 
> 界面本土化，适合国内用户的遥控器操作习惯，比国外的洋软件，比如kodi、Tivimate等等众多IPTV播放器好用多了。
> 
> 该软件为空壳APP，无内置信号源，需要手动填写fanmingming的直播源。
> 
> 奉上本人保存的该软件包，阿里云盘最近分享规则变了，改用中国移动的和彩云云盘永久分享
> 
> https://caiyun.139.com/m/i?035CgisrZZwqg
> 
> 提取码：DAPg

安装后，节目地址填入：https://fanmingming.com/txt?url=https://live.fanmingming.com/tv/m3u/global.m3u，EPG填入：https://live.fanmingming.com/e.xml，无法显示节目单啊，请问是不是还有填别的什么？

**Comment by xibeilang0616** [comment]
不需要，检查输入地址是否正确，是否多一个或少一个字母，或空格什么的

**Comment by beyondth** [comment]
帮忙看看这个DIYP影音是不是节目单也需要特殊解码才行，因为节目单都需要在前边加个https://fanmingming.com/txt?url=呢，谢谢啊！

**Comment by xibeilang0616** [comment]
> 帮忙看看这个DIYP影音是不是EPG项也需要特殊解码才行，因为节目单都需要在前边加个[https://fanmingming.com/txt?url=呢，谢谢啊！](https://fanmingming.com/txt?url=%E5%91%A2%EF%BC%8C%E8%B0%A2%E8%B0%A2%E5%95%8A%EF%BC%81)

乱填，肯定出问题

**Comment by beyondth** [comment]
> > 帮忙看看这个DIYP影音是不是EPG项也需要特殊解码才行，因为节目单都需要在前边加个[https://fanmingming.com/txt?url=呢，谢谢啊！](https://fanmingming.com/txt?url=%E5%91%A2%EF%BC%8C%E8%B0%A2%E8%B0%A2%E5%95%8A%EF%BC%81)
> 
> 乱填，肯定出问题 作为小白，只要填第一行，其他全部删除成空白，就行了，不受影响。

节目地址光填https://live.fanmingming.com/e.xml显示不了中文，无法播放，是不是只能填https://fanmingming.com/txt?url=https://live.fanmingming.com/tv/m3u/global.m3u这个啊？

**Comment by xibeilang0616** [comment]
> > > 帮忙看看这个DIYP影音是不是EPG项也需要特殊解码才行，因为节目单都需要在前边加个[https://fanmingming.com/txt?url=呢，谢谢啊！](https://fanmingming.com/txt?url=%E5%91%A2%EF%BC%8C%E8%B0%A2%E8%B0%A2%E5%95%8A%EF%BC%81)
> > 
> > 
> > 乱填，肯定出问题 作为小白，只要填第一行，其他全部删除成空白，就行了，不受影响。
> 
> 节目地址光填[https://live.fanmingming.com/e.xml电视台显示有很多乱码，无法播放，是不是只能填https://fanmingming.com/txt?url=https://live.fanmingming.com/tv/m3u/global.m3u这个啊？](https://live.fanmingming.com/e.xml%E7%94%B5%E8%A7%86%E5%8F%B0%E6%98%BE%E7%A4%BA%E6%9C%89%E5%BE%88%E5%A4%9A%E4%B9%B1%E7%A0%81%EF%BC%8C%E6%97%A0%E6%B3%95%E6%92%AD%E6%94%BE%EF%BC%8C%E6%98%AF%E4%B8%8D%E6%98%AF%E5%8F%AA%E8%83%BD%E5%A1%ABhttps://fanmingming.com/txt?url=https://live.fanmingming.com/tv/m3u/global.m3u%E8%BF%99%E4%B8%AA%E5%95%8A%EF%BC%9F)

这是一条完整的地址，你非要人为的把一条地址拆分成两节。

**Comment by beyondth** [comment]
帮忙确认下DIYP现在能显示EPG和回看节目吗

**Comment by beyondth** [comment]
还有个问题就是现在只有tivimate能回看，别的试过都不行，不知道咋回事，比如iptv pro、progtv这些都只能看直播，虽然能显示EPG，但都回看不了

**Comment by yalicez** [comment]
用雷鸟模拟器测试了一下V6源回放，播放器是tivimate2.8，失败

**Comment by beyondth** [comment]
真心希望找到除了tivimate以外能读取EPG能正常回看的APP，DIYP影音读不出来EPG啊

**Comment by beyondth** [comment]
> 不会玩，真没办法。有些事情只能自己去慢慢的折腾、摸索、学习、总结、成长。

请问你DIYP影音EPG接口填的什么？我的死活出不来EPG信息

**Comment by xibeilang0616** [comment]
> > 不会玩，真没办法。有些事情只能自己去慢慢的折腾、摸索、学习、总结、成长。
> 
> 请问你DIYP影音EPG接口填的什么？我的死活出不来EPG信息

是不是节目信息？好像不支持，节目信息好像用处不大

**Comment by 168rgp** [comment]
节目单EPG填这个试试
https://epg.112114.eu.org/

**Comment by beyondth** [comment]
> 节目单EPG填这个试试 https://epg.112114.eu.org/

高手啊！之前都是填这个网页里边显示的https://epg.112114.xyz/pp.xml这个一直不成功，现在直接填这个https://epg.112114.eu.org/网页地址就OK了！

不知道啥原理，有没有人能解释一下啊

**Comment by qixuan87** [comment]
目前的IPV6源似乎都不支持回看啊
