### ISSUE TITLE
iptv pro、progtv无法回看啊，请帮忙解决，谢谢！

### ISSUE THREAD

**Issue by beyondth** [fanmingming/live#127]
## 遇到的问题	
请在此描述您遇到的问题。

## 您使用的源
如：IPv6、Global或Radio

## 有问题的频道名称
在此填写的频道名称。

**Comment by beyondth** [comment]
能正常显示节目单，可就是无法回看播放

**Comment by xibeilang0616** [comment]
以下的V6源能完美回看，粘贴复制

https://fanmingming.com/txt?url=https://live.fanmingming.com/tv/m3u/v6.m3u

**Comment by yalicez** [comment]
用哪一个app回放v6源

**Comment by xibeilang0616** [comment]
推荐简单易用APP：DIYP影音

界面本土化，适合国内用户的遥控器操作习惯，比国外的洋软件，比如kodi、Tivimate等等众多IPTV播放器好用多了。

该软件为空壳APP，无内置信号源，需要手动填写fanmingming的直播源。

奉上本人保存的该软件包，阿里云盘最近分享规则变了，改用中国移动的和彩云云盘永久分享

https://caiyun.139.com/m/i?035CgisrZZwqg

提取码：DAPg

**Comment by fanmingming** [comment]
关于回放：源本身是支持回放的，需要通过支持回放的播放器应用来实现回看。
关于有些app不支持m3u格式订阅，请通过项目工具的M3U To TXT Demo链接配合使用。

**Comment by yalicez** [comment]
范明明的global源，我测试的安卓播放器都无法会看，只有ios的aptv是可以回看的。
