### ISSUE TITLE
epg信息无法显示

### ISSUE THREAD

**Issue by Mitchell08** [fanmingming/live#128]
安卓机顶盒，tivimate客户端，节目视频能播放，但是无法显示epg信息，大家有碰到这样情况吗？

![photo_3_2023-10-11_22-54-09](https://github.com/fanmingming/live/assets/13077075/763a3efe-4960-4fcc-b104-c6ef71061d46)
![photo_1_2023-10-11_22-54-09](https://github.com/fanmingming/live/assets/13077075/7d27ec07-4781-4761-8bac-4929e0e7b549)
![photo_2_2023-10-11_22-54-09](https://github.com/fanmingming/live/assets/13077075/ab27dd8d-1e2a-478d-ad2e-c0083f33f3f5)

**Comment by yalicez** [comment]
我也遇到过，后来解决办法是tivimate卸载后重新安装再导入直播源，就又有了，估计是tivimate破解版的bug，但是tivimate其他版安装后总是闪退，没法用

**Comment by yalicez** [comment]
我也遇到过，后来解决办法是tivimate卸载后重新安装再导入直播源，就又有了，估计是tivimate破解版的bug，但是tivimate其他版安装后总是闪退，没法用

**Comment by yalicez** [comment]
我也遇到过，后来解决办法是tivimate卸载后重新安装再导入直播源，就又有了，估计是tivimate破解版的bug，但是tivimate其他版安装后总是闪退，没法用

**Comment by fanmingming** [comment]
感谢反馈！不显示节目单可以尝试退出软件重新进入或者手动刷新EPG。如果你使用的是非正版软件，也可能是破解软件自身的bug导致的。
