### ISSUE TITLE
EPG接口地址： 有问题

### ISSUE THREAD

**Issue by xibeilang0616** [fanmingming/live#131]
fanmingming：你好

反馈贵网提供的EPG有问题
EPG接口地址：
https://live.fanmingming.com/e.xml

很大一部分的m3u直播APP，从来没有显示过频道节目信息。
不经意间试验该论坛其他网友提供的EPG接口

https://epg.112114.eu.org/

立马显示频道节目信息
不知什么原因？
 那就推荐大家使用以下EPG接口

https://epg.112114.eu.org/

**Comment by fanmingming** [comment]
感谢反馈！
根目录下的e.xml实际上是112114的分发，每小时自动更新构建的。如果您使用的是tvbox或diyp类播放软件e.xml是无法正常显示节目单内容的。
目前国内大多数将订阅转换为txt使用的播放软件都没有适配xml格式的EPG内容。

**Comment by xibeilang0616** [comment]
> 感谢反馈！ 根目录下的e.xml实际上是112114的分发，每小时自动更新构建的。如果您使用的是tvbox或diyp类播放软件e.xml是无法正常显示节目单内容的。 目前国内大多数将订阅转换为txt使用的播放软件都没有适配xml格式的EPG内容。

应该增加两到三个EPG接口，让不同的用户和不同APP之间的EPG链接进行尝试。

**Comment by yalicez** [comment]
测了一下tivimate、diyp影音、tvbox，aptv（iOS），这个接口确认反应很快，而且支持txt订阅

**Comment by fanmingming** [comment]
感谢！【关于节目单的问题这里统一回复下】EPG接口的问题，需要播放软件来适配xml格式。项目提供的m3u格式直播源已经内置了EPG，了解到有大量用户使用的是txt格式直播源，所以添加了一个m3u转换txt格式的工具方便他们观看。diyp和tvbox类软件可以继续使用 https://epg.112114.eu.org/ 。考虑到个人精力有限，暂不会添加diyp和tvbox类的epg接口。
