### ISSUE TITLE
请问可以添加这几个CCTV的频道吗

### ISSUE THREAD

**Issue by Funfir3s** [fanmingming/live#133]
CCTV兵器科技、CCTV第一剧场、,CCTV风云剧场、CCTV风云音乐、CCTV怀旧剧场、CCTV女性时尚、CCTV世界地理、CCTV文化精品。我在其他地方看到别人分享的直播源，清晰度不错，就是不知道会不会失效。如果可以的话我把节目链接发给你。

**Comment by fanmingming** [comment]
感谢反馈，目前有一套，下次更新会添加这些频道。
