### ISSUE TITLE
live.fanmingming.com被墙了

### ISSUE THREAD

**Issue by fqw000** [fanmingming/live#134]
RT

**Comment by xibeilang0616** [comment]
怪不得这段时间登录该网特别慢，以前是一眨眼的速度

**Comment by fanmingming** [comment]
![IMG_2778](https://github.com/fanmingming/live/assets/4993993/ee6f307b-b958-4c40-a8b7-f58d37d7c2d5)

经测试，可正常访问。请检查自身的网络存在的问题。
