### ISSUE TITLE
Global源好像无法使用回看功能

### ISSUE THREAD

**Issue by sunqiuming526** [fanmingming/live#135]
## 遇到的问题	
Global源好像确实无法使用回看功能。使用的软件是AppleTV平台的APTV和TV+均已测试, 无法使用回看功能。

## 您使用的源
Global

## 有问题的频道名称
暂时没有发现可用的频道。

**Comment by fanmingming** [comment]
感谢反馈问题。关于回看的问题，请联系相关软件作者解决bug。
