### ISSUE TITLE
手机可以播放IPV6的直播源么？

### ISSUE THREAD

**Issue by caizi86** [fanmingming/live#136]
## 意见建议

按你说的，电脑端的ipv6搞定了，想问一下手机可以播放IPV6的直播源么？我试了VLC和nplayer都不行。。。

**Comment by fanmingming** [comment]
请在手机连接网络的状态下通过浏览器访问 https://www.test-ipv6.com/index.html.zh_CN 进行测试。若测试通过请尝试播放。如果无法播放，请断开当前网络使用手机的数据网络来播放，若成功播放请检查本地网络的问题。若播放不成功，可能是你的运营商有限制或播放器以及本地的IPv6 DNS有问题…

**Comment by caizi86** [comment]
你给的测试地址电脑可以打开，手机打不开。
http://testipv6.cn/index.html.zh_CN这个地址手机可以打开，测试通过。
VLC播放不了。
nplayer里多数频道打不开如图
![微信图片_20231015213413](https://github.com/fanmingming/live/assets/146305362/1574de33-296f-4bcd-b7f5-3d78d44d6032)
少数等半天能打开很卡，先黑屏然后有声音，才有画面

**Comment by xibeilang0616** [comment]
检查一下自己手机、电脑IP地址有没有2409、2408、240打头一长串的字母数字组合的，不会查，自己度娘。如果光是192.168.1.✘ 192.168.0.✘类似这种的，就是纯IPV4地址，没有IPV6地址，光猫和路由器没有设置好，自己不会设置，让专业人士。如果光猫和路由器设备太老古董，不支持IPV6，请更换最新设备。

如果发现有类似这样的2409、2408、240e打头一长串字母数字组合，后面还有192.168.1.✘ ，这叫IP地址双栈协议。支持IPV6的网站或服务器走IPV6通道，不支持的老网站，走IPV4通道。

如果电脑有2409、2408、240e打头的一长串，那手机是强行自动支持IPV6，手机里没有手动设置IPV6的选项。
再检查检查你的播放器设置是否错误。
