### ISSUE TITLE
怎么使用啊~

### ISSUE THREAD

**Issue by TaoJing96** [fanmingming/live#137]
外行小白想请假一下怎么使用

**Comment by xibeilang0616** [comment]
参考本人的帖子进行折腾、学习、使用。

https://github.com/fanmingming/live/issues/56

**Comment by wxhzhwxhzh** [comment]
> 外行小白想请假一下怎么使用

电脑下载一个PotPlayer  ，或者任何一款可以播放流媒体的本地播放器都可以！
