### ISSUE TITLE
有没有正确的食用方式？

### ISSUE THREAD

**Issue by DoBtMe** [fanmingming/live#138]
看了一会是真不明白怎么用的

**Comment by Wuli-Blizzard** [comment]
下载一个potplayer，然后把你下载的那三条链接都用potplayer打开就可以了

**Comment by Wuli-Blizzard** [comment]
> 看了一会是真不明白怎么用的

下载一个potplayer，然后把你下载的那三条链接都用potplayer打开就可以了
