### ISSUE TITLE
新人请教大湿问题

### ISSUE THREAD

**Issue by bmw7cc** [fanmingming/live#139]
## 遇到的问题	
求安卓TV和安卓手机实用的，轻量级的，免费好用的m3u8客户端播放器

## 您使用的源
IPv6、Global或Radio

**Comment by sun123489** [comment]
http://www.videolan.org/vlc/

**Comment by xibeilang0616** [comment]
推荐一个QQ群：780533549，有看电视需求的人士，群文件里面里面的直播空壳APP，五花八门，多如牛毛。
里面的直播APP适合国人简单易用的操作习惯，比洋APP好用多了
