### ISSUE TITLE
https加密证书

### ISSUE THREAD

**Issue by sun123489** [fanmingming/live#140]
## 遇到的问题	
安卓电视安装VLC客户端但是电视没有自带证书https加密TLS握手提示错误无法播放
有没有解决办法啊
我在VLC论坛发帖子了
您这里有没有http不加密的直播源

## 您使用的源
Global直播源
https://live.fanmingming.com/tv/m3u/global.m3u

**Comment by fanmingming** [comment]
感谢提问。非常抱歉，暂无可提供的http协议的IPv4节目源，若设备支持IPv6，建议使用IPv6源来观看。
