### ISSUE TITLE
tivimate2.1.5回放报错

### ISSUE THREAD

**Issue by ZhangXY-Magic** [fanmingming/live#141]
## 遇到的问题	
tivimate2.1.5回放报错
![image](https://github.com/fanmingming/live/assets/25630228/3436cb9e-b663-41d6-91fb-6d3d71a96501)

## 您使用的源
使用global源

## 有问题的频道名称
在此填写的频道名称。

**Comment by fanmingming** [comment]
感谢反馈问题。破解版Tivimate软件可能存在bug，建议使用最新tivimate 4.7.0。

**Comment by mr-chenwu** [comment]
大佬真的辛苦了。自从star后 ，每天都看到大佬坚持维护回答问题。偶像啊
