### ISSUE TITLE
直播源网页播放器打不开

### ISSUE THREAD

**Issue by luban-7** [fanmingming/live#144]
## 遇到的问题	
为什么potplay可以正常播放，网页上的播放器播放不了？
比如:https://cntv.sbs/tv?auth=2310201855&id=cctv6

## 您使用的源
如：Global、Radio

## 有问题的频道名称
在此填写的频道名称。

**Comment by luban-7** [comment]
好像是网页播放有跨域问题

**Comment by fanmingming** [comment]
感谢反馈问题，您可以安装浏览器的hls插件来实现单个节目频道的播放。
