### ISSUE TITLE
需要挂梯子才能顺利播放。

### ISSUE THREAD

**Issue by newtypexyz** [fanmingming/live#149]
## 遇到的问题	
请在此描述您遇到的问题。
之前播放没问题，现在需要挂梯子才能播放，不然会黑屏。
## 您使用的源
如：IPv6、Global或Radio

## 有问题的频道名称
在此填写的频道名称。

**Comment by fanmingming** [comment]
![IMG_2813](https://github.com/fanmingming/live/assets/4993993/3654ef15-f44a-489d-b411-b83fef5ce03b)

感谢反馈，经测试国内可正常访问。请检查自己的网络环境或者更换网络环境来使用。
