### ISSUE TITLE
我这里频道从64到93都没声音，麻烦请检查测试下。谢谢

### ISSUE THREAD

**Issue by YuanHong071** [fanmingming/live#152]
我这里频道从64到93都没声音，麻烦请检查测试下，上次更新也有此问题。谢谢

**Comment by fanmingming** [comment]
感谢反馈问题，经测试正常，可能是您的播放器解码存在问题或设置软\硬解的方式来尝试播放。如还是无法播放，请更换其他播放器再次尝试。

**Comment by YuanHong071** [comment]
谢谢你的回复


范明明 ***@***.***>於 2023年10月27日 週五，12:26寫道：
