### ISSUE TITLE
近日来卡顿

### ISSUE THREAD

**Issue by liyufeng303** [fanmingming/live#155]
我是最近才发现你的这个项目的，用了您的源在前几天播放是很顺畅的，可是这几天发现非常的卡顿，切台困难，我用的是KODI，在用其他源时是没有问题的。请抽空检查一下原因。谢谢！
## 您使用的源
如：IPv6、Global或Radio

## 有问题的频道名称
在此填写的频道名称。

**Comment by klcb2010** [comment]
同   今天发现所有源都卡顿  相对好的是Global源  但部分频道很卡 如 辽宁卫视
