### ISSUE TITLE
Global直播源部分频道无法播放

### ISSUE THREAD

**Issue by Darnix** [fanmingming/live#156]
## 遇到的问题	
使用 PotPlayer 播放 10.29 的Global直播源，无法播放翡翠台和明珠台，请协助排查，谢谢。

## 您使用的源
Global直播源

## 有问题的频道名称
翡翠台、明珠台

**Comment by klcb2010** [comment]
我试了一下也不行  其他台也有卡顿情况

**Comment by twfjcn** [comment]
同样问题，望修复

**Comment by fanmingming** [comment]
感谢反馈，翡翠明珠系列失效了，下午或者晚上会抽空更新。

**Comment by fanmingming** [comment]
翡翠明珠系列已修复，希望能用久一点。

**Comment by fanmingming** [comment]
> > 翡翠明珠系列已修复，希望能用久一点。
> 
> 貌似今天全部都不行了……提示获取🥹

抱歉！域名DNS出现了问题，正在逐步恢复。
