### ISSUE TITLE
不能直连播放，需要挂全局梯子才能使用

### ISSUE THREAD

**Issue by yanggetit** [fanmingming/live#157]
## 遇到的问题	
请在此描述您遇到的问题。

## 您使用的源
如：IPv6、Global或Radio

## 有问题的频道名称
在此填写的频道名称。

**Comment by fanmingming** [comment]
感谢反馈，麻烦提供下您使用的网络运营商以及所在地区。

**Comment by yanggetit** [comment]
﻿中国移动，河南省。现在是在苹果端，软件是APTV，不挂梯子就直接超时，挂了梯子可以更新，但看不了。安卓端：软件是iptv pro，不挂梯子不能观看，挂了梯子可以正常观看。发自我的 iPad发自我的 iPad在 2023年11月3日，19:32，范明明 ***@***.***> 写道：﻿
感谢反馈，麻烦提供下您使用的网络运营商以及所在地区。

**Comment by fanmingming** [comment]
再次感谢您的反馈。已更改域名的NS Server，部分地区无法获取播放列表的问题会在24小时内随着DNS生效自动恢复。
