### ISSUE TITLE
湖北江汉联通无法使用

### ISSUE THREAD

**Issue by jenova14** [fanmingming/live#158]
## 遇到的问题	
请在此描述您遇到的问题。

## 您使用的源
如：IPv6、Global或Radio

## 有问题的频道名称
在此填写的频道名称。

**Comment by daxiahu** [comment]
我也是，联通宽带，这两周突然就无法使用了，之前一直在用

**Comment by jenova14** [comment]
> 我也是，联通宽带，这两周突然就无法使用了，之前一直在用

我连了个电信节点就又能用了

**Comment by fanmingming** [comment]
已更改域名的NS Server，部分地区无法获取播放列表的问题会在24小时内随着DNS生效自动恢复。
