### ISSUE TITLE
GLOBAL节目

### ISSUE THREAD

**Issue by victozhong** [fanmingming/live#164]
## 遇到的问题	
GLOBAL节目在广东的东莞无法播放

## 您使用的源
GLOBAL 源，IPV6没问题

## 有问题的频道名称
所有频道都是一样的问题

**Comment by fanmingming** [comment]
感谢您的反馈。已更改域名的NS Server，部分地区无法获取播放列表的问题会在24小时内随着DNS生效自动恢复。
