### ISSUE TITLE
Emby 无法观看直播源

### ISSUE THREAD

**Issue by QYQSDTC** [fanmingming/live#165]
## 遇到的问题	
通过 Emby 添加直播源无法观看

## 您使用的源
Global

## 有问题的频道名称
CCTV
---------
![CleanShot-23YyM7tB@2x](https://github.com/fanmingming/live/assets/15608306/78289a0c-f569-4e46-8e4e-c758ac713940)
![CleanShot-6wEeUhQm@2x](https://github.com/fanmingming/live/assets/15608306/9163046b-ff70-42ac-b0d8-4c1afc368c84)
显示无兼容的流

**Comment by fanmingming** [comment]
感谢反馈问题。看到您的列表名称似乎与m3u当中的命名有区别，请先删除emby当中的订阅源重新添加后再次尝试使用。若还是无法使用，建议直接通过支持m3u格式的播放器来添加订阅使用。
