### ISSUE TITLE
xbox iptv 📺IPTV(IPV6专用)无法使用

### ISSUE THREAD

**Issue by Tinyblur** [fanmingming/live#175]
## 遇到的问题	
在xbox的iptv中配置📺IPTV(IPV6专用)源后，页面可正常解析出直播信息(甚至包含了每一个电视台的播放列表都可以看到)，但是无法观看

## 您使用的源
IPv6

## 有问题的频道名称
所有

![微信图片_20231111183805](https://github.com/fanmingming/live/assets/57427484/06e6e538-4a67-420b-b482-87e69cc15aff)

**Comment by fanmingming** [comment]
感谢反馈，使用IPv6源需要您的设备可以正常获取到公网IPv6地址。关于如何开启IPv6您可通过各大搜索引擎获得相关信息。

**Comment by Tinyblur** [comment]
okok，感谢！！我试试
