### ISSUE TITLE
更新了2023/11/10号播放源以后，感觉视频加载比之前慢了。有时播放直播视频发现音频比字幕有点拖 画质也没有之前的清晰了 

### ISSUE THREAD

**Issue by fifaplayer88** [fanmingming/live#176]
## 遇到的问题	
更新了11/10号播放源以后，感觉视频频道从一个频道切换到另外一个频道加载比之前慢了。有时播放直播视频发现音频比字幕有点拖 画质也没有之前的清晰了  如 CCTV8或者 CCTV1

## 您使用的源
Global直播源 https://live.fanmingming.com/tv/m3u/global.m3u)
## 有问题的频道名称
更新了11/10号播放源以后，感觉视频频道从一个频道切换到另外一个频道加载比之前慢了。有时播放直播视频发现音频比字幕有点拖 画质也没有之前的清晰了  如 CCTV8或者 CCTV1

**Comment by xibeilang0616** [comment]
IPTV4本身时间延迟特别长，IPV6秒开。
尽量用IPV6，检查一下自己网络有没有开通IPV6，如没有，让宽带维护人员换光猫或者设置光猫，路由器也要支持IPV6

**Comment by fifaplayer88** [comment]
> IPTV4本身时间延迟特别长，IPV6秒开。 尽量用IPV6，检查一下自己网络有没有开通IPV6，如没有，让宽带维护人员换光猫或者设置光猫，路由器也要支持IPV6

可惜我这边还没有支持IPV6 ，但是我觉得之前的源切换还是比较快的 还是等fanmingming兄弟来看看 有没有办法解决吧

**Comment by fanmingming** [comment]
感谢反馈，11月10日的更新更换了节目源，新的节目源需要等待跳转资源后才能正常播放，请耐心等待节目跳转成功。后面有更好用更快的节目源也会做进一步优化和更新。

**Comment by xibeilang0616** [comment]
> > IPTV4本身时间延迟特别长，IPV6秒开。 尽量用IPV6，检查一下自己网络有没有开通IPV6，如没有，让宽带维护人员换光猫或者设置光猫，路由器也要支持IPV6
> 
> 可惜我这边还没有支持IPV6 ，但是我觉得之前的源切换还是比较快的 还是等fanmingming兄弟来看看 有没有办法解决吧

全国各运营商现在都支持IPV6，可能光猫和路由器没有设置好，也可能是你路由器太老，不支持IPV6
