### ISSUE TITLE
麻烦重新换源  切换速度太慢了

### ISSUE THREAD

**Issue by tiyuban123** [fanmingming/live#178]
1.  11.10源  放在影音，影视仓  tvbox等切换速度明显比之前慢很多
2. 导出成txt  放到diyp目录下  不支持播放  拿单个cctv播放链接放在mx player播放器也不支持播放，放在浏览器倒是可以播放，搞不懂啥原因

**Comment by xibeilang0616** [comment]
IPTV4本身时间延迟特别长，IPV6秒开。
用过IPV6的，再也不想用IPV4了。
尽量用IPV6，检查一下自己网络有没有开通IPV6，如没有，让宽带维护人员换光猫或者设置光猫，路由器也要支持IPV6。

**Comment by fanmingming** [comment]
感谢反馈，11月10日的更新更换了节目源，新的节目源需要等待跳转资源后才能正常播放，请耐心等待节目跳转成功。后面有更好用更快的节目源也会做进一步优化和更新。
