### ISSUE TITLE
用potplayer播放时有画面没声音咋回事

### ISSUE THREAD

**Issue by blockclover** [fanmingming/live#179]
## 遇到的问题	
请在此描述您遇到的问题。

## 您使用的源
如：IPv6、Global或Radio

## 有问题的频道名称
在此填写的频道名称。

**Comment by blockclover** [comment]
用potplayer播放时有画面没声音咋回事

**Comment by fanmingming** [comment]
感谢反馈问题，PotPlayer播放器无声音的问题建议找到“Shift+x 开启声音滤镜”选项关闭或开启，然后再次点击要观看的频道。

**Comment by blockclover** [comment]
你好，还是不行

**Comment by fanmingming** [comment]
打开PotPlayer 找到 “声音” —— “声音处理”——“规格化” 选择，试试看。
如果还不行，建议搜索“PotPlayer 有画面 没声音”查找关于PotPlayer问题的解决办法。
