### ISSUE TITLE
直播源经常失效，总是需要更新，怎么能自动下载更新直播源呢。

### ISSUE THREAD

**Issue by hytk1989** [fanmingming/live#181]
如题。直播源经常失效，我是在电视上看的，直播源失效了，就重新下载，导入U盘，再导入电视，太麻烦了。怎么能实现自动更新直播源，或者至少是自动下载你更新的直播源，然后替换到原来的。

**Comment by fanmingming** [comment]
感谢反馈，直播源的每个频道都具有一定的时效性，建议通过在线订阅的形式来使用直播源，如果您的播放器支持启动自动更新源，建议打开自动更新开关。若播放器使用的是txt格式的直播源，项目已经提供了m3u转txt的工具，您可通过转换后的链接，以订阅的方式来使用。

**Comment by hytk1989** [comment]
> 感谢反馈，直播源的每个频道都具有一定的时效性，建议通过在线订阅的形式来使用直播源，如果您的播放器支持启动自动更新源，建议打开自动更新开关。若播放器使用的是txt格式的直播源，项目已经提供了m3u转txt的工具，您可通过转换后的链接，以订阅的方式来使用。

我家里的电视上使用的是tivimate，不知道有没有其他支持自动更新源的直播软件推荐呢？
