### ISSUE TITLE
劲爆体育频道的直播没有了吗

### ISSUE THREAD

**Issue by cirolchou** [fanmingming/live#182]
## 遇到的问题	
今天打开Global源之后发现列表里没有劲爆体育频道了，请问是因为直播不稳定所以把这个频道删除了吗？多谢

## 您使用的源
Global

## 有问题的频道名称
劲爆体育

**Comment by fanmingming** [comment]
感谢提问，目前Global源更换了大多数频道的节目源。原节目源经过近几日测试，多条线路都不是非常稳定(失效较快)，有相对稳定线路的情况下原来的频道可能也会更新回来，还请继续关注项目日后的更新。
