### ISSUE TITLE
ipv6 凤凰系列和 newtv 系列播放不了

### ISSUE THREAD

**Issue by wai998** [fanmingming/live#183]
ipv6 凤凰系列和 newtv 系列播放不了

**Comment by fanmingming** [comment]
感谢反馈，经测试可正常播放。请检查自己的网络连接是否正常。

**Comment by 5a43** [comment]
ipv4的凤凰卫视看不了，凤凰资讯台没有了

**Comment by fanmingming** [comment]
> ipv4的凤凰卫视看不了，凤凰资讯台没有了

凤凰两个频道都失效了。如果有IPv6网络建议使用IPv6源来观看凤凰中文、资讯和香港三个频道。
