### ISSUE TITLE
希望能继续提供五星体育的播放源

### ISSUE THREAD

**Issue by ZhouXJCDC** [fanmingming/live#184]
## 遇到的问题	
11.10更新后没有上海五星体育了，希望大佬能够恢复此频道， 提前感谢~

## 您使用的源
Global

## 有问题的频道名称
在此填写的频道名称。

**Comment by fanmingming** [comment]
感谢提问，目前Global源更换了大多数频道的节目源。原节目源经过近几日测试，多条线路都不是非常稳定(失效较快)，有相对稳定线路的情况下原来的频道可能也会更新回来，还请继续关注项目日后的更新。
