### ISSUE TITLE
五星

### ISSUE THREAD

**Issue by junwang0204** [fanmingming/live#189]
## 遇到的问题	
请在此描述您遇到的问题。
Global 没有五星体育啊
## 您使用的源
如：IPv6、Global或Radio
Global
## 有问题的频道名称
在此填写的频道名称。
五星体育

**Comment by fanmingming** [comment]
非常抱歉，当前暂不提供五星体育频道的节目源。有相对稳定的节目源后面也会做相应的更新，还请继续关注项目日后的更新。谢谢。
