### ISSUE TITLE
可否考虑在极狐上开源项目

### ISSUE THREAD

**Issue by klcb2010** [fanmingming/live#19]
如踢 ，你懂的  目前所在平台有时候很不稳定   难以访问  极狐没有这个痛点

**Comment by fanmingming** [comment]
感谢关注，目前暂不考虑在其他平台开源和托管。live.fanmingming.com生成的所有内容都是由GitHub自动构建自动更新的。如国内无法直连访问的情况下会考虑更换托管平台。
