### ISSUE TITLE
两个问题 

### ISSUE THREAD

**Issue by wangbf007** [fanmingming/live#190]
## 遇到的问题	
问题一：ipv6 北京纪实频道是否失效了？播放不了 。问题二：为何Global直播源在 科学上网 网络环境下（PC端和安卓手机端）能正常播放，但是ipv6直播源只能关了机场才能播放？在此感谢项目及主理人fanmingming！

## 您使用的源
IPv6、Global

## 有问题的频道名称
北京纪实频道（ipv6）

**Comment by wangbf007** [comment]
第二个问题补充说明：在Mac系统上，不关机场 ipv6源也能播放。纳闷了为何pc平台和安卓手机只能关了机场才可以播ipv6源？

**Comment by fanmingming** [comment]
非常感谢您的提醒，纪实科教频道的IPv6节目源现已修复。
关于IPv6源在开启VPN状态下无法播放的情况，如您的VPN服务供应商提供有IPv6+IPv4双栈接入的节点，应该是您的VPN软件禁用了设备的IPv6网络。若您的VPN服务商仅提供IPv4节点，请您查找VPN软件有关“开启IPv6或网络兼容性增强”等功能的选项来使用IPv6直播源。

**Comment by wangbf007** [comment]
感谢解惑第二个问题！ 原来是没开启代理软件ipv6开关嘿嘿...
