### ISSUE TITLE
大佬 咨询一下，访问快慢的问题和ipv6的问题

### ISSUE THREAD

**Issue by xiaolongzhou123** [fanmingming/live#193]
## 遇到的问题	
1. ipv6下，其它终端都用什么能播放(ipv6.m3u)？只有windows的potplayer可以放ipv6那个
2. cntv.lat播放太慢，正常都怎么加速的？我让cntv.lat走香港节点。也感觉慢，走本地直连也慢（北京）

家里已经开启了ipv6，在电脑上通过potplayer是可以播放那个ipv6的。
1. vlc无法播放
4. ios找的Iptv播放器也不行，也放不了
5. android的iptv播放器也不行，

**Comment by xibeilang0616** [comment]
用DIYP影音

界面跟电视家非常类似，符合大屏电视，符合国人的遥控器操作习惯，简单易用，容易上手。
洋APP，适合小众折腾者和程序猿，对大众不太友好，不适合老人使用。

用bing搜索，不建议国内搜索引擎，广告太多，信息错乱，
或者在微信里搜索“DIYP影音”，要甄别，山寨DIYP的太多，本来想推荐给你QQ群，群主fanmingming有限制，不让直接推荐APP，自己动手，丰衣足食。

**Comment by fanmingming** [comment]
感谢提问，直播源均收集自互联网。项目无法保证提供的直播节目源能适配所有播放器或应用，且无法保证每个频道的有效性。非常抱歉！
