### ISSUE TITLE
关于xteve/emby/plex等程序上的使用

### ISSUE THREAD

**Issue by onelxzy** [fanmingming/live#194]
## 遇到的问题	
我通过potplayer测试得知直播源本身应该（至少绝大部分）可用，但是我发现最近不少频道的地址被更换为了php跳转，我理解这样可能是为了匹配多个接口遇到失效时方便切换，但似乎这种地址在xteve等程序上不被支持。是否可以考虑保留一个全是m3u8地址的直播源，以便此直播源可以用于Xteve。

## 您使用的源
Global

## 有问题的频道名称
所有使用php跳转的频道

**Comment by fanmingming** [comment]
感谢提问，直播源均收集自互联网。项目无法保证提供的直播节目源能适配所有播放器或应用，且无法保证每个频道的有效性。非常抱歉！
