### ISSUE TITLE
如何整理成像作者一样的m3u

### ISSUE THREAD

**Issue by flyhelanman** [fanmingming/live#201]
## 意见建议
作者的直播源是我见过整理最好的了，我是一个小白，最近某些原因才接触kodi+m3u这种新兴事物，我有一个问题，作者能否帮忙解答一下，我其实在git上找到了一些直播源地址，比如:
https://iptv-org.github.io/iptv/countries/cn.m3u
https://epg.pw/test_channels_china_country.m3u
但是在kodi添加源后显示如下，我在想是否可以在这些已有的m3u基础上二次开发或者整理，最终达到作者的源显示一样
![image](https://github.com/fanmingming/live/assets/18319435/3f73e7fb-3855-465b-b7e8-d58cd021717c)
![image](https://github.com/fanmingming/live/assets/18319435/ed2cc9e9-9522-46f2-b17f-fb0b6cfcc797)

这里面是否涉及两个问题：
1.如果格式化显示，用到了EPG?
2.如何批量check有效性

或者作者是否考虑出个教程贴，自己做m3u源，针对自己有一台小型服务器的人来说可以动手尝试一下。感谢。

**Comment by liuchuancong** [comment]
第一步呢，先学会爬虫，爬取哪些内容或者关键字，第二步：测试爬取的东西是否有效，第三步：使用githip action 自动构建爬虫
第四步：构建好了自动更新项目

**Comment by flyhelanman** [comment]
> 第一步呢，先学会爬虫，爬取哪些内容或者关键字，第二步：测试爬取的东西是否有效，第三步：使用githip action 自动构建爬虫 第四步：构建好了自动更新项目

大概去搜了下抓包相关的东西，首先是从哪里抓包，我看有通过iptv盒子抓包，不同地区盒子貌似又有区别，有通过pc播放抓包的，比如央视频，但是如果抓到可用的m3u8，又涉及到加密算法，总体来说对一个小白来说难度有点大

**Comment by flyhelanman** [comment]
刚发现m3u的文件可以通过txt打开，类似下图
![image](https://github.com/fanmingming/live/assets/18319435/7364dc85-d485-4489-861d-88337d050ac1)
也就是说找到可用的m3u8列表，然后设置每个的格式就可以了，那么问题来了，看来重点还是如何找到m3u8，或者如何抓到明文源地址才是难点

> 第一步呢，先学会爬虫，爬取哪些内容或者关键字，第二步：测试爬取的东西是否有效，第三步：使用githip action 自动构建爬虫 第四步：构建好了自动更新项目

刚发现m3u的文件可以通过txt打开，类似下图
![image](https://github.com/fanmingming/live/assets/18319435/7364dc85-d485-4489-861d-88337d050ac1)
也就是说找到可用的m3u8列表，然后设置每个的格式就可以了，那么问题来了，看来重点还是如何找到m3u8，或者如何抓到明文源地址才是难点

**Comment by flyhelanman** [comment]
> 第一步呢，先学会爬虫，爬取哪些内容或者关键字，第二步：测试爬取的东西是否有效，第三步：使用githip action 自动构建爬虫 第四步：构建好了自动更新项目

刚发现m3u的文件可以通过txt打开，类似下图
![image](https://github.com/fanmingming/live/assets/18319435/7364dc85-d485-4489-861d-88337d050ac1)
也就是说找到可用的m3u8列表，然后设置每个的格式就可以了，那么问题来了，看来重点还是如何找到m3u8，或者如何抓到明文源地址才是难点

**Comment by liuchuancong** [comment]
逆向工程 直接官网爬

**Comment by flyhelanman** [comment]
> 逆向工程 直接官网爬

对普通用户来说，先不说学习成本，光是从哪里学习，找资料就有点难度了，可以精确推荐一些学习资料吗，比如我的目的是抓取央视频直播源，那么我需要在B站哪个UP主学习相关知识，我的意思是稍微具体精确一些的意见，不是宽泛的概念，谢谢回复。
