### ISSUE TITLE
可以增加无锡地方电视台吗~

### ISSUE THREAD

**Issue by haixiao91** [fanmingming/live#203]
## 意见建议
可以增加无锡地方电视台吗~
无锡娱乐,http://stream.thmz.com/wxtv2/playlist.m3u8
无锡新闻综合,http://stream.thmz.com/wxtv1/playlist.m3u8
无锡生活,http://stream.thmz.com/wxtv4/playlist.m3u8
无锡经济,http://stream.thmz.com/wxtv5/playlist.m3u8
无锡都市资讯,http://stream.thmz.com/wxtv3/playlist.m3u8

**Comment by xibeilang0616** [comment]
如果加全国各市、县、区电视台，那数量太多了，工作量巨大，
像自己区域的地方台自己加工成无锡频道·TXT文件放在一些直播软件的专属文件夹，就能直播APP观看自己设计的频道
