### ISSUE TITLE
回放问题

### ISSUE THREAD

**Issue by Ck-247** [fanmingming/live#205]
您好，我从大概2个月前开始，使用tivimate播放您的播放源，前段时间更新里提到新增了回放功能后，我发现回放功能确实可以用了，不过最近我发现回放功能好像失效了？我得咨询下，是回放格式发生了变化，所以我需要做出某种修改才能继续兼容吗？

**Comment by xibeilang0616** [comment]
目前IPV6直播源的回放和时移功能不健全，有少量的频道有回放功能，比如凤凰卫视。
 
给你fanmingming另一个IPV6直播源，每个频道都能回放和时移，配合DIYP影音使用，回放和时移，简单易用，爽歪歪！

tivimate使用这个链接
https://live.fanmingming.com/tv/m3u/v6.m3u

DIYP使用这个链接
https://fanmingming.com/txt?url=https://live.fanmingming.com/tv/m3u/v6.m3u

**Comment by ixbcqq** [comment]
楼上这个厉害啊，为啥这么好的链接没有公开放出来呢？

**Comment by Ck-247** [comment]
非常感谢！我这边已经试过了，确实非常好用.

**Comment by xibeilang0616** [comment]
> 楼上这个厉害啊，为啥这么好的链接没有公开放出来呢？

这个是压箱底的，自个儿用的，一般人不告诉他，😄

**Comment by cnjerry828** [comment]
> 目前IPV6直播源的回放和时移功能不健全，有少量的频道有回放功能，比如凤凰卫视。
> 
> 给你fanmingming另一个IPV6直播源，每个频道都能回放和时移，配合DIYP影音使用，回放和时移，简单易用，爽歪歪！
> 
> tivimate使用这个链接 https://live.fanmingming.com/tv/m3u/v6.m3u
> 
> DIYP影音使用这个链接 https://fanmingming.com/txt?url=https://live.fanmingming.com/tv/m3u/v6.m3u

实测rtivimate无法回看，提示err 400

**Comment by xibeilang0616** [comment]
> > 目前IPV6直播源的回放和时移功能不健全，有少量的频道有回放功能，比如凤凰卫视。
> > 给你fanmingming另一个IPV6直播源，每个频道都能回放和时移，配合DIYP影音使用，回放和时移，简单易用，爽歪歪！
> > tivimate使用这个链接 https://live.fanmingming.com/tv/m3u/v6.m3u
> > DIYP影音使用这个链接 https://fanmingming.com/txt?url=https://live.fanmingming.com/tv/m3u/v6.m3u
> 
> 实测rtivimate无法回看，提示err 400

我这一年了到现在好好的，可能播放器的原因，更换一个播放器看看，比如DIYP影音，

**Comment by cnjerry828** [comment]
> > > 目前IPV6直播源的回放和时移功能不健全，有少量的频道有回放功能，比如凤凰卫视。
> > > 给你fanmingming另一个IPV6直播源，每个频道都能回放和时移，配合DIYP影音使用，回放和时移，简单易用，爽歪歪！
> > > tivimate使用这个链接 https://live.fanmingming.com/tv/m3u/v6.m3u
> > > DIYP影音使用这个链接 https://fanmingming.com/txt?url=https://live.fanmingming.com/tv/m3u/v6.m3u
> > 
> > 
> > 实测rtivimate无法回看，提示err 400
> 
> 我这一年了到现在好好的，可能播放器的原因，更换一个播放器看看，比如DIYP影音，

试过OTT也不行。DIYP还没有试过

**Comment by zhouchang2017** [comment]
kodi回看设置
请求格式字符串：?starttime={utc:YmdTHMS}&endtime={utcend:YmdTHMS}
回放修正：8小时
