### ISSUE TITLE
global全部挂啦。

### ISSUE THREAD

**Issue by mr-chenwu** [fanmingming/live#207]
## 遇到的问题	
国内源文件全部挂了。

## 您使用的源
global

## 有问题的频道名称
国内源文件全部挂了。

最近大环境问题，大佬辛苦啦。难道真的到了说再见的时候了吗啊？依依不舍啊

**Comment by JerryFoundation** [comment]
用爱发电，终归没了

**Comment by tangwenixng** [comment]
广电终究还是挥起了大刀

**Comment by dayunnas** [comment]
广电难不成还能管到GitHub？

**Comment by yuanfirst** [comment]
📔更新
2023.11.22
抱歉！Global源即日起不再提供。


终究还是只能这样了
