### ISSUE TITLE
Global用不了了ipv6的那个可以用吗？

### ISSUE THREAD

**Issue by suyang320** [fanmingming/live#208]

**Comment by mr-chenwu** [comment]
可以

**Comment by JerryFoundation** [comment]
挂了挺多

**Comment by kilaterlee** [comment]
Ipv6源需要开ipv6吗？

**Comment by xibeilang0616** [comment]
> Ipv6源需要开ipv6吗？

升级为IPV6网络，也谈不上升级，就是懂技术会折腾的人把光猫设置一下IPV6双栈协议。不管光猫原来是拨号，

重点来了，还是人为的手动光猫设置桥接模式，路由器拨号，重要的是光猫桥接模式也要设置IPV4&IPV6双协议。不然，路由器仍然无法获取到IPV6地址。

路由器相对简单，找到IPV6选项打开就行了。不会的，打电话宽带客服请宽带维护人员设置光猫或更换不支持IPV6老光猫。

**Comment by meng17603883819** [comment]
> Ipv6源需要开ipv6吗？猫和路由器都要开。
