### ISSUE TITLE
电脑能播，电视和手机不能播

### ISSUE THREAD

**Issue by rabholly** [fanmingming/live#209]
用的 IPTV(IPV6专用) 源，有人指导下吗？
 app 试了 IPTV pro tivimate DIYP影音，都不行

**Comment by xibeilang0616** [comment]
别人都好好的
点击下面链接检测自己网络是否完美支持IPV6，检测页面自己要能看懂

https://ipv6-test.netcologne.de/index.html.zh_CN``

**Comment by DAHEIEHAD** [comment]
你的网络是否支持ipv6呢？源是没问题的。

**Comment by rabholly** [comment]
同一部手机，同一个网络，换了 `Kodi` 可以
感觉像是不同播放器对 `ipv6` 支持的默认设置不一样

**Comment by xibeilang0616** [comment]
> 同一部手机，同一个网络，换了 `Kodi` 可以 感觉像是不同播放器对 `ipv6` 支持的默认设置不一样

第一次听说IPV6对播放器默认设置不一样这种奇特的理论，不要乱甩锅。自己排查不了，请专业人士排查，

**Comment by rabholly** [comment]
> > 同一部手机，同一个网络，换了 `Kodi` 可以 感觉像是不同播放器对 `ipv6` 支持的默认设置不一样
> 
> 第一次听说IPV6对播放器默认设置不一样这种奇特的理论，不要乱甩锅。自己排查不了，请专业人士排查，

请问我甩锅给谁了？我提问就是希望有人指导下，看你的回复，不知道哪来的优越感🤢

**Comment by shuanglinqiancheng** [comment]
我也和你一样，电脑和ipad能用，模拟器和手机不能用，不知道什么原因

**Comment by rmlau** [comment]
我现在的情况，同一个直播源：
1. 同wifi网络下电脑用potplayer正常；
2. 电视上安装Kodi不能播放
3. 电视盒子（Apple TV）上，用iPlayTV和APTV不能播放，ipv6地址是好的，用emby播放ipv6源也没问题

**Comment by liuhui19994** [comment]
我也是同一网络下，iplay tv不播放，TV+可以，PC也可以

**Comment by liuhui19994** [comment]
我也同网络下，iplay tv不播放，TV+可以，PC也可以,aptv添加源地址无法下载节目，m3u下载到本地再上传到aptv却可以，有点玄学

**Comment by rmlau** [comment]
我换APTV好像就可以了，免费版挂两个源播放都正常

Andy ***@***.***> 于 2024年1月11日周四 23:07写道：

**Comment by xlilium** [comment]
> 别人都好好的 点击下面链接检测自己网络是否完美支持IPV6，检测页面自己要能看懂
> 
> https://ipv6-test.netcologne.de/index.html.zh_CN

您好，我的电脑和手机连家里的网都可以通过这个测试，但是a p tv软件还是只显示正在使用ipv4网络，所以源都显示超时，请问该怎么处理呀？谢谢

**Comment by jasonding121205** [comment]
我也很奇怪，源肯定没问题。手机fileball就能播，电脑vlc/potplayer盒子kodi/tivimate都没法播

**Comment by xlilium** [comment]
> 我也很奇怪，源肯定没问题。手机fileball就能播，电脑vlc/potplayer盒子kodi/tivimate都没法播

谢谢回复！我最后换了个路由器好啦，之前用的比较简单的蒲公英路由器，关于ipv6的设置比较少，新买的红米的打开ipv6的上网方式为native就可以了
