### ISSUE TITLE
能否说明下有关Global源即日起不再提供的具体原因

### ISSUE THREAD

**Issue by fifaplayer88** [fanmingming/live#212]
## 遇到的问题	
能否说明下有关Global源即日起不再提供的具体原因

## 您使用的源
https://live.fanmingming.com/tv/m3u/global.m3u)

## 有问题的频道名称
能否说明下有关Global源即日起不再提供的具体原因,及以后都不再更新这个项目了吗？

**Comment by fanmingming** [comment]
感谢关注，详细请看置顶说明。
