### ISSUE TITLE
电视用的tivimate软件添加IPTV播放源看不了

### ISSUE THREAD

**Issue by porkie2016** [fanmingming/live#214]
![1](https://github.com/fanmingming/live/assets/20235064/f4fcdd98-d812-437a-94b1-2b32e214cece)
## 遇到的问题	
请在此描述您遇到的问题。

## 您使用的源
如：IPv6、Global或Radio

## 有问题的频道名称
在此填写的频道名称。
![2](https://github.com/fanmingming/live/assets/20235064/7c489165-d055-4e6e-8d0e-63a7119e9f1b)

**Comment by xibeilang0616** [comment]
kodi、IPTV Pro、tivimate、OTT都用过。没有任何问题。估计是你粘贴复制过程中有瑕疵，误操作

**Comment by doem97** [comment]
> > kodi、IPTV Pro、tivimate、OTT都用过。没有任何问题。 看你的IP地址好像在美国。 不知道真美国IP地址，还是爬梯子的IP美国地址 如果是在国内爬梯子的IP地址，还是真美国IP地址，无法观看国内IPV6直播的。 我试过用翻墙地址是无法看的。
> 
> 的确是这样，已解决感谢

Hi porkie how do u solved this? Also not in mainland
