### ISSUE TITLE
部分台画面和声音不同步

### ISSUE THREAD

**Issue by opqrst123** [fanmingming/live#218]
## 遇到的问题	
遇到部分台画面和声音不同步 

## 您使用的源
IPV6

## 有问题的频道名称
使用kodi观看cctv1和cctv2 东方卫视 声音不同步
但我看其他的台 如cctv6 cctv8 北京卫视 又是没问题的

**Comment by xibeilang0616** [comment]
前段时间我试用OTT也有这样毛病，音画不同步，果断卸载。
kodi这一类洋APP，看似显得高大上，使用者觉得高端，能装逼以外，功能多是多，其实稳定性差，不建议使用，对于普通大众菜单操作繁琐，界面不太友好，不适合家中老人使用，IPTV插件开启缓慢，好长时间没用过这玩意。

建议DIYP、百川这一类空壳，简单专业，适合大众，稳定可靠，启动快，换台快。
让专业APP干专业的事。

**Comment by opqrst123** [comment]
> 前段时间我试用OTT也有这样毛病，音画不同步，果断卸载。 kodi这一类洋APP，看似显得高大上，使用者觉得高端，能装逼以外，功能多是多，吃硬件资源，其实稳定性差，不建议使用。 对于普通大众菜单操作繁琐，界面不太友好，不适合家中老人使用，IPTV插件开启缓慢，好长时间没用过这玩意。
> 
> 建议DIYP、百川这一类空壳，简单专业，适合大众，稳定可靠，启动快，换台快。 让专业APP干专业的事。

谢谢推荐 我试试去
