### ISSUE TITLE
ipv6频道无法观看，但是ipv6连通性已经通过

### ISSUE THREAD

**Issue by pizzacloud** [fanmingming/live#219]
## 遇到的问题	
ipv6的央视和地方卫视无法观看。经测试我的网络是ipv6网络，有线无线都测试过。
## 您使用的源
如：IPv6

## 有问题的频道名称
所有

**Comment by xibeilang0616** [comment]
最好贴图，一看故障就知道

**Comment by pizzacloud** [comment]
![Screenshot_20231125_114915](https://github.com/fanmingming/live/assets/54195144/15a98909-5b65-4281-b0aa-527f6f7cb342)
这是手机在外面的，在家里ipv6测试结果相同，手机和电视显示相同

**Comment by pizzacloud** [comment]
![Screenshot_20231125_121314_edit_2978483902664](https://github.com/fanmingming/live/assets/54195144/ad1daccc-48c9-479d-b310-47af64de2d32)
手机端
![Screenshot_20231125_114807](https://github.com/fanmingming/live/assets/54195144/773ed2cd-6a7d-4f6b-a1a9-8ac8d14872e9)
和电视端，流量和无线，都是这样的结果

**Comment by xibeilang0616** [comment]
不知用的什么APP

**Comment by Aegiszhy** [comment]
你用的是IPTV（蓝色图标）吧，那个软件播放部分IPV6地址的源会出BUG，你可以尝试其他IPTV软件例如Tivimate

**Comment by xibeilang0616** [comment]
> 你用的是IPTV（蓝色图标）吧，那个软件播放部分IPV6地址的源会出BUG，你可以尝试其他IPTV软件例如Tivimate

不是，DIYP影音

**Comment by pizzacloud** [comment]
我用tivimate在电视上也不行

**Comment by xibeilang0616** [comment]
> 我用tivimate在电视上也不行

是不是地址填写错误？
https://live.fanmingming.com/tv/m3u/ipv6.m3u

是不是填写的这个？

tivimate是m3u播放器
DIYP是.txt的播放器

**Comment by pizzacloud** [comment]
我的手机没有安装diyp，tivimate我装的是m3u没有问题的，这里面的外国频道和部分地方台可以播

**Comment by pizzacloud** [comment]
如果有diyp的下载地址可以给我下，谢谢

**Comment by xibeilang0616** [comment]
> 如果有diyp的下载地址可以给我下，谢谢

DIYP影音0606台标集成正式版
https://www.aliyundrive.com/s/snpzhU6r9nn

**Comment by pizzacloud** [comment]
文件夹是空的

**Comment by xibeilang0616** [comment]
> 文件夹是空的

DIYP影音0606台标集成正式版
https://www.aliyundrive.com/s/wYRVSwU4SCV

**Comment by pizzacloud** [comment]
仍然是空的

**Comment by xibeilang0616** [comment]
阿里云盘文件类型分享不了

**Comment by Aegiszhy** [comment]
你也可以尝试如下方案：先下个mxplayer，然后在IPTV软件上选择用第三方播放器播放，然后看能不能播放源，我碰到过这种情况已经可以排除不是源的问题

**Comment by pizzacloud** [comment]
我倾向于认为是我自己网络的问题，因为用了多个iptv播放器结果都是一样的。

**Comment by xibeilang0616** [comment]
> 我倾向于认为是我自己网络的问题，因为用了多个iptv播放器结果都是一样的。

你把地址所有的信息磨的一点儿都看不见。没办法判断

**Comment by Aegiszhy** [comment]
你也可以尝试用局域网内其他的设备进行测试，例如用局域网内一台连通了IPV6的PC进行测试，使用VLC或者MPV去播放m3u列表；或者使用流量进行播放，因为现如今的手机端数据流量一般都支持V6连通

**Comment by pizzacloud** [comment]
好的非常感谢。对技术不了解，就都抹去了

**Comment by pizzacloud** [comment]
第三方播放器也无法播放。我的邮箱fgschn@qq.com

**Comment by xibeilang0616** [comment]
> 第三方播放器也无法播放。我的邮箱[fgschn@qq.com](mailto:fgschn@qq.com)

已发送，请查收

**Comment by xibeilang0616** [comment]
> > 第三方播放器也无法播放。我的邮箱[fgschn@qq.com](mailto:fgschn@qq.com)
> 
> 已发送，请查收

发送成功，请查收

**Comment by xibeilang0616** [comment]
> > > 第三方播放器也无法播放。我的邮箱[fgschn@qq.com](mailto:fgschn@qq.com)
> > 
> > 
> > 已发送，请查收
> 
> 发送成功，请查收

安装后粘贴复制以下DIYP的地址
https://fanmingming.com/txt?url=https://live.fanmingming.com/tv/m3u/ipv6.m3u

**Comment by meng17603883819** [comment]
这个跟你网络也有关系，比如在一个屋子里联通的手机网络就看不了星空卫视，移动宽带就能。

**Comment by TOPGUUN** [comment]
你用手机上testipv6.cn,如果通过了就是你app问题,不然就是自己问题,安卓开下飞行模式再关闭看看
