### ISSUE TITLE
现在范明明能像以前那样弄一个一键订阅的傻瓜式链接吗

### ISSUE THREAD

**Issue by z496596474** [fanmingming/live#226]
我实在是看不懂改版后的教程

**Comment by fanmingming** [comment]
Global源的订阅往后不再提供了，项目所有内容都可以通过【https://live.fanmingming.com/{项目的目录名称/文件名}】方式引用。
实际上首页工具中M3U转TXT的Demo已经有一个m3u订阅链接了。需要txt格式就使用完整地址，不需要转换可以直接复制后面的m3u链接。

**Comment by xibeilang0616** [comment]
> Global源的订阅往后不再提供了，项目所有内容都可以通过【[https://live.fanmingming.com/{项目的目录名称/文件名}】方式引用。](https://live.fanmingming.com/%7B%E9%A1%B9%E7%9B%AE%E7%9A%84%E7%9B%AE%E5%BD%95%E5%90%8D%E7%A7%B0/%E6%96%87%E4%BB%B6%E5%90%8D%7D%E3%80%91%E6%96%B9%E5%BC%8F%E5%BC%95%E7%94%A8%E3%80%82) 实际上首页工具中M3U转TXT的Demo已经有一个m3u订阅链接了。需要txt格式就使用完整地址，不需要转换可以直接复制后面的m3u链接。

那么长的地址，一般人玩不了
