### ISSUE TITLE
连WiFi看不了，换流量就可以

### ISSUE THREAD

**Issue by ywp824** [fanmingming/live#231]
您好，连WiFi看不了，换流量就可以，这是为什么，怎么解决，谢谢

**Comment by TOPGUUN** [comment]
说明你wifi没ipv6

**Comment by xibeilang0616** [comment]
升级为IPV6网络，也谈不上升级，就是懂技术会折腾的人把光猫设置一下IPV6双栈协议。不管光猫原来是拨号，还是光猫桥接，路由器拨号。

重点来了，人为手动光猫设置桥接模式，路由器拨号，重要的是光猫桥接模式也要设置IPV4&IPV6双协议。不然，路由器拨号后仍然无法获取到IPV6地址。

路由器相对简单，找到IPV6选项打开就行了。
路由器支持IPV6比较晚，近四五年内中高端路由器才支持IPV6，。

不会的，打电话宽带客服请宽带维护人员设置光猫IPV6
，或更换用了十几年前的不支持IPV6老光猫，。
