### ISSUE TITLE
fanmingming主页挂了

### ISSUE THREAD

**Issue by xibeilang0616** [fanmingming/live#232]
是政策原因，还是没有续费的原因，目前不得而知
这会通过节目接口链接收看直播的广大用户电视中所有的频道消失，
如果以前下载过的m3u文件的不收影响
![Screenshot_2023-12-12-09-11-27-380_com android browser](https://github.com/fanmingming/live/assets/56585354/8a095808-5dd0-4058-8482-94e84feb6ed5)
![Screenshot_2023-12-12-09-52-59-991_com android browser](https://github.com/fanmingming/live/assets/56585354/6450a8b9-920a-4115-b220-650960a39df8)

**Comment by fanmingming** [comment]
感谢反馈，应该是ssl证书因为套了cloudflare续期没有续上导致的错误。已经更新dns设置了。耐心等待生效就好了。非常抱歉。

**Comment by xibeilang0616** [comment]
> 感谢反馈，应该是ssl证书因为套了cloudflare续期没有续上导致的错误。已经更新dns设置了。耐心等待生效就好了。非常抱歉。

已经正常了
