### ISSUE TITLE
大佬，能发个教程，怎么获取ipv6的数据源吗？

### ISSUE THREAD

**Issue by Jiangzqts** [fanmingming/live#233]
## 意见建议
在广电的高压下，怕以后很难看到大佬更新直播源，所以想自己尝试获取直播源，自己在浏览器查看页面，获取到的直播地址，打开之后有声音，但是花屏，所以希望大佬能分享下获取直播源的方法

**Comment by fanmingming** [comment]
浏览器可以播放的用开发者工具F12抓取，App类型的用抓包软件。盒子内置的通过PC双网卡网桥获取。相关的问题可以去Google搜索下相关文章或视频学习吧。
