### ISSUE TITLE
请问能给 ipv6.m3u 生成一个支持回放的版本吗？

### ISSUE THREAD

**Issue by FanchangWang** [fanmingming/live#237]
请问能给 ipv6.m3u 生成一个支持回放的版本吗？不然每次更新后都得自己替换再上传 github

非常感谢 👍

**Comment by fanmingming** [comment]
可以回看的源可以使用v6.m3u

**Comment by FanchangWang** [comment]
> 可以回看的源可以使用v6.m3u

v6.m3u 的源地址跟 ipv6.m3u 不一样，我这里只能播放 ipv6.m3u 的地址
