### ISSUE TITLE
大佬能出个教程吗

### ISSUE THREAD

**Issue by Re-hd** [fanmingming/live#24]
大佬能不能对如何配置的平台和方法给出一些建议或教程？因为这方面不了解。
非常感谢。

**Comment by fanmingming** [comment]
感谢提问：
项目仅提供m3u格式的直播源。
Windows系统推荐使用PotPlayer。
Android可使用Kodi或其他支持m3u的播放器。
iOS可使用ntplayer或者aptv(支持Apple全平台)。
