### ISSUE TITLE
tv/m3u/ipv6.m3u 中陕西频道中一行有两个tvg-name，其中一个tvg-name应该改为tvg-id

### ISSUE THREAD

**Issue by MCaveMan** [fanmingming/live#242]
tv/m3u/ipv6.m3u 中陕西频道中一行有两个tvg-name，其中一个tvg-name应该改为tvg-id
![微信截图_20240119093937](https://github.com/fanmingming/live/assets/1560027/ef14d67c-dded-43e3-b8a3-47ac06a87b5d)

**Comment by fanmingming** [comment]
感谢，马上修正！
