### ISSUE TITLE
回放失效

### ISSUE THREAD

**Issue by pengpeng0512** [fanmingming/live#246]
https://github.com/fanmingming/live/blob/main/tv/m3u/ipv6.m3u
Kodi不可回放
<img width="650" alt="Snipaste_2024-02-05_09-57-47" src="https://github.com/fanmingming/live/assets/158707724/6f75fef8-f63e-4a62-808b-064a3afe24a3">
Kodi可回放
<img width="653" alt="Snipaste_2024-02-05_09-56-17" src="https://github.com/fanmingming/live/assets/158707724/ecb9db92-544a-46a3-b485-d2ec90116b5a">
烦请@fanmingming 大佬修改

**Comment by pengpeng0512** [comment]
Potplayer和Tivimate没问题，看来是Kodi的问题。

**Comment by fanmingming** [comment]
感谢反馈，关于回看的问题可能是前置IP导致的。后面会慢慢修复。

**Comment by pengpeng0512** [comment]
> 感谢反馈，关于回看的问题可能是前置IP导致的。后面会慢慢修复。

多谢大佬！

**Comment by pengpeng0512** [comment]
> 感谢反馈，关于回看的问题可能是前置IP导致的。后面会慢慢修复。
