### ISSUE TITLE
求助大佬怎么看回放

### ISSUE THREAD

**Issue by dongguaguaguagua** [fanmingming/live#252]
我一开始用的是`ipv6.m3u`，用的KODI iptv-simple-client插件。在回放功能中将格式字符串设置为`?playseek=${(b)yyyyMMddHHmmss}-${(e)yyyyMMddHHmmss}`，但是看不了回放。然后我搜索issue https://github.com/fanmingming/live/issues/237 得知`v6.m3u`可以看回放。但是该源在 b5a5c82 中被删除了，而且将它导入KODI后还是看不了回放。问问大佬是不是现在看不了回放了，还是KODI没有正确设置呢？

KODI设置：
<img width="542" alt="图片" src="https://github.com/fanmingming/live/assets/57585727/2775bd2e-96ac-44a9-9d7c-79657519d376">

报错信息：
<img width="399" alt="error" src="https://github.com/fanmingming/live/assets/57585727/32f84775-e2b9-4c74-b7b9-a35df59167af">

日志信息：
<img width="960" alt="log" src="https://github.com/fanmingming/live/assets/57585727/eb9b22be-e320-4af3-b9e2-e855fef2712b">

**Comment by beyondth** [comment]
同求解决啊

**Comment by beyondth** [comment]
电脑上要想找一个能回看的软件，太难了

**Comment by pengpeng0512** [comment]
请求格式字符串?playseek={utc:YmdHMS}-{utcend:YmdHMS}
回放窗口时间-7天
所有频道支持的回放使用模式-追加
从电子节目单观看（使用时移-打开
左侧时移-启用
以上设置完右上角-确定
回到Kodi主界面-设置-PVR和直播电视-指南-显示的过去日数-7天
配合以下大佬分享的历史直播源可实现回看
[https://github.com/fanmingming/live/blob/506f88ee4915c8d225533e85ae4d1a7f43f767f1/tv/m3u/ipv6.m3u](url)
[https://github.com/fanmingming/live/blob/6c3cd7e48c2fadaa0ab0f30a2f2480a403fba9f9/tv/m3u/ipv6.m3u](url)
直接订阅大佬的最新直播源貌似回看失效了[https://github.com/fanmingming/live/issues/246](url)
