### ISSUE TITLE
ipv6 源是失效了么

### ISSUE THREAD

**Issue by xjxjin** [fanmingming/live#254]
我添加了ipv6源，频道一直在循环切换
<img width="943" alt="image" src="https://github.com/fanmingming/live/assets/35513148/c4530445-c28e-4daf-a667-758216264c40">

**Comment by xjxjin** [comment]
https://live.fanmingming.com/tv/m3u/ipv6.m3u，这个是我添加的地址

**Comment by j530168483** [comment]
添加代理或者挂梯子试试

**Comment by pengpeng0512** [comment]
IPV6连接测试
https://test-ipv6.com/

**Comment by xjxjin** [comment]
<img width="1025" alt="image" src="https://github.com/fanmingming/live/assets/35513148/2c63d6c2-e788-4935-b95e-fc7e110f11f0">
ipv6是打开的，之前用的挺好的，就是新更新之后就放不了
