### ISSUE TITLE
疑问

### ISSUE THREAD

**Issue by lurudong** [fanmingming/live#259]
## 遇到的问题	
请在此描述您遇到的问题。

一定要把demo.m3u上传GItHubt上？

参考下方示例代码将可用的CCTV1节目源替换为您当地可用的直播源链接，依此类推逐个替换。

#EXTM3U x-tvg-url="https://live.fanmingming.com/e.xml"
#EXTINF:-1 tvg-id="CCTV1" tvg-name="CCTV1" tvg-logo="https://live.fanmingming.com/tv/CCTV1.png" group-title="央视",CCTV-1 综合
可用的CCTV1节目源
此处省略...
将编辑完成的m3u文件上传到您的Github仓库。
为您的Github仓库开启Pages。
通过播放器订阅您的m3u链接。

**************************
我可以直接使用你提供的源吗??

**Comment by xboy880710** [comment]
新人同问

**Comment by ChambersXDU** [comment]
直接使用仓库里的ipv6.m3u即可

**Comment by xboy880710** [comment]
仓库里的ipv6.m3u为何不能直接复制网址当订阅地址，下载m3u文件导入的话需要定期重新下载，比较麻烦

**Comment by fanmingming** [comment]
> 仓库里的ipv6.m3u为何不能直接复制网址当订阅地址，下载m3u文件导入的话需要定期重新下载，比较麻烦

[https://live.fanmingming.com/tv/m3u/ipv6.m3u](https://fanmingming.com/txt?url=https://live.fanmingming.com/tv/m3u/ipv6.m3u)
