### ISSUE TITLE
请教怎么把EPG 项目forks到复制国内仓库?

### ISSUE THREAD

**Issue by xibeilang0616** [fanmingming/live#262]
因为国内112114所有的EGP接口都被墙了，TVbox、DIYP的接口都被封死了，节目信息没有了，回看也不方便了

有一个想法，想把贵项目或者112114项目forks到国内码云等仓库，有什么教程么？，请各位大佬赐教

又想forks的项目，又想设置成DIYP的EPG接口，私用
有什么办法吗？

**Comment by PKC278** [comment]
可以直接部署到cloudflare等cdn站点
