### ISSUE TITLE
怎么直接使用github action这个直接把主分支main的e.xml更新了，不使用本地git推送到云端，直接把云端更新可以么？有代码么？

### ISSUE THREAD

**Issue by SteveDarnell** [fanmingming/live#265]
## 遇到的问题	
请在此描述您遇到的问题。

**Comment by fanmingming** [comment]
参考下/.github/workflows目录的内容。

**Comment by SteveDarnell** [comment]
> 参考下/.github/workflows目录的内容。

老哥，我参考了你的代码，里面用户名和邮件地址怎么设置？需要用到本地git么？如果没有本地git，代码怎么编辑。
