### ISSUE TITLE
直播源失效

### ISSUE THREAD

**Issue by DIAO11** [fanmingming/live#268]

**Comment by jiaoluo2022** [comment]
确实看不了，请问还维护吗？

**Comment by runnrest** [comment]
请问如何用URL添加到tivimate？
我试图添加，但是没有任何频道信息

**Comment by dominicx** [comment]
> 今天的源更新后手机上用ntplayer看不了了，电视上用Tivimate看很不稳定很卡

我是tivimate 看不了。tivimate 2.8
电脑potplayer可以看。

**Comment by Kurthang** [comment]
昨天可用，今天一个都看不了了，tivimate

**Comment by sobigworm** [comment]
确实看不了了

**Comment by yanglogo** [comment]
今天早上全部不能看了，希望大佬能帮忙解决，谢谢

**Comment by wulala2173** [comment]
貌似和epg关闭服务器有关

**Comment by fanmingming** [comment]
最近有点忙，因为目前条件有限，维护只能靠手机，希望大家担待下。问题先关了。

**Comment by yanglogo** [comment]
感谢大佬维护，现在又可以看了，tivimate 和电脑都能观看了，非常感谢您百忙中关心大家

**Comment by yanglogo** [comment]
范先生：您好

           好久以前，一直受您关照，我们能顺利观看直播节目，我发现一个问题想和您反馈一下

数字频道的求索科学、求索生活的EPG节目单一直是错误的，很长时间了，我以为每次更新会解决，但是好像到目前为止，EPG的错误还是依旧，

如果可能，请您关注一下，看看能不能修复该问题，万分感激！

 

 

发件人: ***@***.*** ***@***.***> 代表 范明明
发送时间: 2024年4月11日 13:39
收件人: fanmingming/live ***@***.***>
抄送: yanglogo ***@***.***>; Comment ***@***.***>
主题: Re: [fanmingming/live] 直播源失效 (Issue #268)

 

最近有点忙，因为目前条件有限，维护只能靠手机，希望大家担待下。问题先关了。
