### ISSUE TITLE
现在换台很卡，每次都要等4-5秒才能播放

### ISSUE THREAD

**Issue by sln162** [fanmingming/live#269]
现在换台很卡，每次都要等4-5秒才能播放，没有之前快了，以前基本显示2M/s，换台一两秒就可以播放了
现在先显示几百kb/s然后过4秒才显示1m/s，然后才出来画面，每次切台都很慢，是暂时性的修复吗，还是以后都这样了？

**Comment by BOLOSXHY** [comment]
遇到同样问题，PC端，我以为是potplayer卡了

**Comment by lyrasean** [comment]
直播源变了吧，以前的移动IPv6源切换是快，现在应该不是了

**Comment by sln162** [comment]
根据群里的讨论，应该是用的央视的源，明明有点忙，可能没时间整理还可用的v6源，新站点还套了cloudflare，我觉得这是主要原因，我测试了一个国内阿里云服务器的，跟明明现在的方式是这样的，换台快的多，跟之前的v6差不多

**Comment by BOLOSXHY** [comment]
大佬可以分享一下阿里云的源链接吗

**Comment by ixbcqq** [comment]
确实慢了很多，我不应该手痒去更新节目列表

**Comment by peter2022** [comment]
> 确实慢了很多，我不应该手痒去更新节目列表

你不更新 他这个m3u文件里的域名都换了吧？ 我把原来的m3u下到本地，原来的m3u里的域名源应该失效了

**Comment by sln162** [comment]
> 大佬可以分享一下阿里云的源链接吗

留个邮箱吧，公布出来不太好，虽然不是我的

**Comment by fanmingming** [comment]
麻烦刷新下订阅。
