### ISSUE TITLE
请问这个m3u在线文件的使用问题

### ISSUE THREAD

**Issue by peter2022** [fanmingming/live#270]
## 遇到的问题	
请在此描述您遇到的问题。
https://live.fanmingming.com/tv/m3u/ipv6.m3u
请问这个m3u文件我就放到 机顶盒中的tivimate里 就不用每次更新了吗？
那如果是联通的ipv6，m3u的文件是电信或者移动的 是不是就看不了？

**Comment by fanmingming** [comment]
添加到订阅就不需要管了，定期刷新更新就好。
