### ISSUE TITLE
未知频道

### ISSUE THREAD

**Issue by BUYAOXIABB** [fanmingming/live#274]
## 遇到的问题	

IPV6出现未知频道，请大佬修复。

**Comment by BUYAOXIABB** [comment]
频道菜单几里面全是  未知频道
![Screenshot_2024-04-15-18-38-20-68_e18329511ee9ae4541720d804dbbeba9](https://github.com/fanmingming/live/assets/37601100/35fe56c2-433a-456c-b805-03586a178a33)

**Comment by EastLord** [comment]
same here

**Comment by fanmingming** [comment]
不确定是不是由于最后三个频道导致的问题，刚才修复了最后3个频道的问题，请重新刷新源以后再试。如果问题依旧，可以再次开启提问。

**Comment by BUYAOXIABB** [comment]
> 频道菜单几里面全是 未知频道 ![Screenshot_2024-04-15-18-38-20-68_e18329511ee9ae4541720d804dbbeba9](https://private-user-images.githubusercontent.com/37601100/322449289-35fe56c2-433a-456c-b805-03586a178a33.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyMjYzNzAsIm5iZiI6MTcxMzIyNjA3MCwicGF0aCI6Ii8zNzYwMTEwMC8zMjI0NDkyODktMzVmZTU2YzItNDMzYS00NTZjLWI4MDUtMDM1ODZhMTc4YTMzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDAwMDc1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1ZWM5YjIxNTMzNWE0MzM0ZTJiNDMxNjE3ODI2NWU4ZDlkZTZjZGFkMmViMDZhNTE4YzZmYTQ4ZTViOGJkMmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-evQNh63JDfScRShCCi-jYoXPhrUD4DdrbZxAqKDyVE)



kodi版本 20.5
IPTV Simple Client插件 版本 20.13


目前更新最新版还是 全部是未知频道
顺序都是乱的。
![Screenshot_2024-04-16-08-06-47-73_e18329511ee9ae4541720d804dbbeba9](https://github.com/fanmingming/live/assets/37601100/807c87fa-2428-4799-bbe7-217f4ad69abc)

![Screenshot_2024-04-16-08-06-47-73_e18329511ee9ae4541720d804dbbeba9](https://github.com/fanmingming/live/assets/37601100/4b024de5-57ba-4472-a1f7-6ee944879c53)

**Comment by BUYAOXIABB** [comment]
> > 频道菜单几里面全是 未知频道 ![Screenshot_2024-04-15-18-38-20-68_e18329511ee9ae4541720d804dbbeba9](https://private-user-images.githubusercontent.com/37601100/322449289-35fe56c2-433a-456c-b805-03586a178a33.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyMjYzNzAsIm5iZiI6MTcxMzIyNjA3MCwicGF0aCI6Ii8zNzYwMTEwMC8zMjI0NDkyODktMzVmZTU2YzItNDMzYS00NTZjLWI4MDUtMDM1ODZhMTc4YTMzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDAwMDc1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1ZWM5YjIxNTMzNWE0MzM0ZTJiNDMxNjE3ODI2NWU4ZDlkZTZjZGFkMmViMDZhNTE4YzZmYTQ4ZTViOGJkMmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-evQNh63JDfScRShCCi-jYoXPhrUD4DdrbZxAqKDyVE)
> 
> kodi版本 20.5 IPTV Simple Client插件 版本 20.13
> 
> 目前更新最新版还是 全部是未知频道 顺序都是乱的。 ![Screenshot_2024-04-16-08-06-47-73_e18329511ee9ae4541720d804dbbeba9](https://private-user-images.githubusercontent.com/37601100/322660692-807c87fa-2428-4799-bbe7-217f4ad69abc.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyMjY1ODYsIm5iZiI6MTcxMzIyNjI4NiwicGF0aCI6Ii8zNzYwMTEwMC8zMjI2NjA2OTItODA3Yzg3ZmEtMjQyOC00Nzk5LWJiZTctMjE3ZjRhZDY5YWJjLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDAwMTEyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5MzJjNGQ0ZDQ5M2NhZTUxNGM5MWVmYTMxMjY5NjVjNGQ5OWFiODQ2OWFmZTlkY2NkZjU1YjgwNWYwNjgwZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UnQ_xEorLb9SfTPOEu2g3-cZe7M05LgKOlYZUSASqSs)
> 
![Screenshot_2024-04-16-08-06-11-27_fc704e6b13c4fb26bf5e411f75da84f2](https://github.com/fanmingming/live/assets/37601100/6e1bf324-ce57-4511-bb09-6f427aa7cb6f)
