### ISSUE TITLE
最后3个频道有错误

### ISSUE THREAD

**Issue by sobigworm** [fanmingming/live#275]
原内容
#EXTINF:-1 tvg-id="" tvg-name="newtv精品萌宠" tvg-name="newtv精品萌宠" tvg-logo="https://live.fanmingming.com/tv/NEWTV精品萌宠.png"  group-title="数字频道" group-title="",精品萌宠

正确的应该是
#EXTINF:-1 tvg-id="newtv精品萌宠" tvg-name="newtv精品萌宠" tvg-logo="https://live.fanmingming.com/tv/NEWTV精品萌宠.png"  group-title="数字频道",精品萌宠

另外有个问题想请教一下大佬
catchup="append" catchup-source="?playseek=${(b)yyyyMMddHHmmss}-${(e)yyyyMMddHHmmss}" 这段有什么作用啊？

**Comment by fanmingming** [comment]
感谢提醒，已修复。
