### ISSUE TITLE
更新最新后 频道菜单还是 未知频道 

### ISSUE THREAD

**Issue by BUYAOXIABB** [fanmingming/live#276]
> > 频道菜单几里面全是 未知频道 ![Screenshot_2024-04-15-18-38-20-68_e18329511ee9ae4541720d804dbbeba9](https://private-user-images.githubusercontent.com/37601100/322449289-35fe56c2-433a-456c-b805-03586a178a33.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyMjYzNzAsIm5iZiI6MTcxMzIyNjA3MCwicGF0aCI6Ii8zNzYwMTEwMC8zMjI0NDkyODktMzVmZTU2YzItNDMzYS00NTZjLWI4MDUtMDM1ODZhMTc4YTMzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDAwMDc1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1ZWM5YjIxNTMzNWE0MzM0ZTJiNDMxNjE3ODI2NWU4ZDlkZTZjZGFkMmViMDZhNTE4YzZmYTQ4ZTViOGJkMmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-evQNh63JDfScRShCCi-jYoXPhrUD4DdrbZxAqKDyVE)
> 
> kodi版本 20.5 IPTV Simple Client插件 版本 20.13
> 
> 目前更新最新版还是 全部是未知频道 顺序都是乱的。 ![Screenshot_2024-04-16-08-06-47-73_e18329511ee9ae4541720d804dbbeba9](https://private-user-images.githubusercontent.com/37601100/322660692-807c87fa-2428-4799-bbe7-217f4ad69abc.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyMjY1ODYsIm5iZiI6MTcxMzIyNjI4NiwicGF0aCI6Ii8zNzYwMTEwMC8zMjI2NjA2OTItODA3Yzg3ZmEtMjQyOC00Nzk5LWJiZTctMjE3ZjRhZDY5YWJjLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDAwMTEyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5MzJjNGQ0ZDQ5M2NhZTUxNGM5MWVmYTMxMjY5NjVjNGQ5OWFiODQ2OWFmZTlkY2NkZjU1YjgwNWYwNjgwZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UnQ_xEorLb9SfTPOEu2g3-cZe7M05LgKOlYZUSASqSs)
> 
![Screenshot_2024-04-16-08-06-11-27_fc704e6b13c4fb26bf5e411f75da84f2](https://github.com/fanmingming/live/assets/37601100/6e1bf324-ce57-4511-bb09-6f427aa7cb6f)

_Originally posted by @BUYAOXIABB in https://github.com/fanmingming/live/issues/274#issuecomment-2058017517_

**Comment by BUYAOXIABB** [comment]
![Screenshot_2024-04-15-18-38-20-68_e18329511ee9ae4541720d804dbbeba9](https://github.com/fanmingming/live/assets/37601100/bba7d417-ebd8-457c-8411-ad94b196dcdd)

**Comment by lyrasean** [comment]
可能是因为单个频道下有多个链接，试试订阅这个：https://m3u.ibert.me/fmml_ipv6.m3u

**Comment by fanmingming** [comment]
非常抱歉，应该是是一个频道对应多个链接的问题。不过本次修复还要感谢网友 @sln162 ，近期确实是没有时间来处理这些问题。五一左右可能才有时间，只能晚上抽空看下是不是有拉起请求并且处理。

**Comment by BUYAOXIABB** [comment]
> 可能是因为单个频道下有多个链接，试试订阅这个：https://m3u.ibert.me/fmml_ipv6.m3u

这个地址可以使用，感谢！

**Comment by BUYAOXIABB** [comment]
> 非常抱歉，应该是是一个频道对应多个链接的问题。不过本次修复还要感谢网友 @sln162 ，近期确实是没有时间来处理这些问题。五一左右可能才有时间，只能晚上抽空看下是不是有拉起请求并且处理。

感谢大佬，辛苦了。

**Comment by sln162** [comment]
> 非常抱歉，应该是是一个频道对应多个链接的问题。不过本次修复还要感谢网友 @sln162 ，近期确实是没有时间来处理这些问题。五一左右可能才有时间，只能晚上抽空看下是不是有拉起请求并且处理。

客气了，倒是可以更新为一个频道对应一个链接，但是单一的线路可能随时出问题，最近不稳定，HLJ能坚持多久犹未可知。
建议大家使用支持多线路的播放器，比如影视/影视仓/tvbox等等，当一个线路挂了，还能有备用线路能看。

**Comment by fanmingming** [comment]
> > 非常抱歉，应该是是一个频道对应多个链接的问题。不过本次修复还要感谢网友 @sln162 ，近期确实是没有时间来处理这些问题。五一左右可能才有时间，只能晚上抽空看下是不是有拉起请求并且处理。
> 
> 客气了，倒是可以更新为一个频道对应一个链接，但是单一的线路可能随时出问题，最近不稳定，HLJ能坚持多久犹未可知。 建议大家使用支持多线路的播放器，比如影视/影视仓/tvbox等等，当一个线路挂了，还能有备用线路能看。

其实每个频道多个源可以独立出来整理成分组。不清楚您是否有时间来完成维护，比如把分组放到最后央视备用1、2、3卫视备用1、2类似这种。后面有失效维护也能方便些。
还有，项目是完全开源的，谁都可以编辑。衷心感谢每一位参与过live项目的热心网友！🙏

**Comment by dryBranch** [comment]
> > > 非常抱歉，应该是是一个频道对应多个链接的问题。不过本次修复还要感谢网友 @sln162 ，近期确实是没有时间来处理这些问题。五一左右可能才有时间，只能晚上抽空看下是不是有拉起请求并且处理。
> > 
> > 
> > 客气了，倒是可以更新为一个频道对应一个链接，但是单一的线路可能随时出问题，最近不稳定，HLJ能坚持多久犹未可知。 建议大家使用支持多线路的播放器，比如影视/影视仓/tvbox等等，当一个线路挂了，还能有备用线路能看。
> 
> 其实每个频道多个源可以独立出来整理成分组。不清楚您是否有时间来完成维护，比如把分组放到最后央视备用1、2、3卫视备用1、2类似这种。后面有失效维护也能方便些。 还有，项目是完全开源的，谁都可以编辑。衷心感谢每一位参与过live项目的热心网友！🙏

如果只是kodi上的插件不支持多线路的话，给kodi单起一个文件过渡一下如何？这样不会影响到现在可用的软件。如果kodi的插件以后可以支持多线路，那么这个临时的就可以去掉了。（PS：可以写一个简单的脚本处理现有m3u文件

**Comment by fanmingming** [comment]
> > > > 非常抱歉，应该是是一个频道对应多个链接的问题。不过本次修复还要感谢网友 @sln162 ，近期确实是没有时间来处理这些问题。五一左右可能才有时间，只能晚上抽空看下是不是有拉起请求并且处理。
> > > 
> > > 
> > > 客气了，倒是可以更新为一个频道对应一个链接，但是单一的线路可能随时出问题，最近不稳定，HLJ能坚持多久犹未可知。 建议大家使用支持多线路的播放器，比如影视/影视仓/tvbox等等，当一个线路挂了，还能有备用线路能看。
> > 
> > 
> > 其实每个频道多个源可以独立出来整理成分组。不清楚您是否有时间来完成维护，比如把分组放到最后央视备用1、2、3卫视备用1、2类似这种。后面有失效维护也能方便些。 还有，项目是完全开源的，谁都可以编辑。衷心感谢每一位参与过live项目的热心网友！🙏
> 
> 如果只是kodi上的插件不支持多线路的话，给kodi单起一个文件过渡一下如何？这样不会影响到现在可用的软件。如果kodi的插件以后可以支持多线路，那么这个临时的就可以去掉了。（PS：可以写一个简单的脚本处理现有m3u文件

最近的审核和维护都是通过手机完成的，所以大范围的改动比较费时费力。非常感谢您的付出！

**Comment by sobigworm** [comment]
> > > > 非常抱歉，应该是是一个频道对应多个链接的问题。不过本次修复还要感谢网友 @sln162 ，近期确实是没有时间来处理这些问题。五一左右可能才有时间，只能晚上抽空看下是不是有拉起请求并且处理。
> > > 
> > > 
> > > 客气了，倒是可以更新为一个频道对应一个链接，但是单一的线路可能随时出问题，最近不稳定，HLJ能坚持多久犹未可知。 建议大家使用支持多线路的播放器，比如影视/影视仓/tvbox等等，当一个线路挂了，还能有备用线路能看。
> > 
> > 
> > 其实每个频道多个源可以独立出来整理成分组。不清楚您是否有时间来完成维护，比如把分组放到最后央视备用1、2、3卫视备用1、2类似这种。后面有失效维护也能方便些。 还有，项目是完全开源的，谁都可以编辑。衷心感谢每一位参与过live项目的热心网友！🙏
> 
> 已经按你的要求（分组放到最后央视备用1、2、3卫视备用1、2）创建了拉起，一共两次提交，一个是央视备用1，然后下面卫视备用1，数字备用1，央视备用2，卫视备用2，数字备用2。 后面的一个提交是改成了，央视备用1，央视备用2，卫视备用1，卫视备用2，数字备用1，数字备用2。
> 
> 具体采用哪个，需要您来定夺，因为第一次提交是我用程序来实现的，第二次是我在第一次的基础上手动编辑的下。

现在这个分组改的很不人性化，对可以自动切换线路的人来说非常的不友好，万一线路1失效还要手动去切换，而且分组过多显的很杂乱。
也并不是所有人都是用Kodi的，如果确实有人有这个需求，个人更建议单独另外建立一个文件
