### ISSUE TITLE
求一个上海新闻综合频道的链接

### ISSUE THREAD

**Issue by taochenwei007** [fanmingming/live#287]
求一个上海新闻综合频道的链接，谢谢~

**Comment by wangbf007** [comment]
#EXTINF:-1 tvg-name="上海新闻" group-title="地方",上海新综
http://[2409:8087:5e08:24::12]:6610/000000001000/2000000002000000005/index.m3u8?stbId=3&livemode=1&HlsProfileId=&channel-id=hnbblive&Contentid=2000000002000000005&IASHttpSessionId=OTT19019320240419154124000281&yang-1989

**Comment by taochenwei007** [comment]
收到，非常感谢~~




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fanmingming/live"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月28日(星期天) 下午2:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fanmingming/live] 求一个上海新闻综合频道的链接 (Issue #287)





 
#EXTINF:-1 tvg-name="上海新闻" group-title="地方",上海新综
 http://[2409:8087:5e08:24::12]:6610/000000001000/2000000002000000005/index.m3u8?stbId=3&amp;livemode=1&amp;HlsProfileId=&amp;channel-id=hnbblive&amp;Contentid=2000000002000000005&amp;IASHttpSessionId=OTT19019320240419154124000281&amp;yang-1989

**Comment by fanmingming** [comment]
感谢提醒，已更新。
