### ISSUE TITLE
直播源更新后视频卡顿了

### ISSUE THREAD

**Issue by ixbcqq** [fanmingming/live#288]
直播源更新后视频卡顿了。最近直播源更新很频繁，有几次更新，看视频是很流畅的。昨晚看电视的时候变卡了，应该是直播源的问题，因为我用手机流量看也是卡顿的。但似乎也没啥好办法，毕竟直播源频繁更新也是无奈之举

**Comment by ixbcqq** [comment]
另外就是可以增加一些国际台吗？例如半岛电视台，挺稳定的

**Comment by fanmingming** [comment]
国际频道的播放体验不是很好，很久前已经全部剔除了，若后面播放体验相对好的情况下会添加上来。感谢您的反馈！
