### ISSUE TITLE
联通网络，白天看不卡，晚上看每一秒就缓冲，非常卡

### ISSUE THREAD

**Issue by 582911658** [fanmingming/live#289]
<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by ixbcqq** [comment]
是的！！我就是这样！！晚上看每一秒就缓冲，非常卡！！我还以为我是个例呢，用手机流量看又是正常的

**Comment by fanmingming** [comment]
可能是运营商高峰期限速的问题。

**Comment by lppsuixn** [comment]
广东联通，也是这样。有解不

**Comment by ixbcqq** [comment]
> 广东联通，也是这样。有解不

刚测试，佛山联通，不卡了

**Comment by lppsuixn** [comment]
> > 广东联通，也是这样。有解不
> 
> 刚测试，佛山联通，不卡了
广州联通，开2s开始卡

**Comment by ixbcqq** [comment]
> > > 广东联通，也是这样。有解不
> > 
> > 
> > 刚测试，佛山联通，不卡了
> > 广州联通，开2s开始卡

又看了一下，佛山联通也卡了，电视和手机都卡

**Comment by ixbcqq** [comment]
> > > > 广东联通，也是这样。有解不
> > > 
> > > 
> > > 刚测试，佛山联通，不卡了
> > > 广州联通，开2s开始卡
> 
> 又看了一下，佛山联通也卡了，电视和手机都卡

WiFi 和流量都卡

**Comment by Shaco-Ma** [comment]
联通+1,晚上巨卡,大家有办法解决吗?

**Comment by ixbcqq** [comment]
> 联通+1,晚上巨卡,大家有办法解决吗?

卡爆了，但正常看爱奇艺或下载视频的网速又是正常的，只有看这个IPTV是卡爆了
