### ISSUE TITLE
求台湾东森  世界地理

### ISSUE THREAD

**Issue by SuperBlackWednesday** [fanmingming/live#29]
这俩台都有版权，很多电影动画都是独播的，尤其是东森电影  感谢。

**Comment by fanmingming** [comment]
东森电影有点卡就没放上去。
http://120.84.96.89:808/hls/32/index.m3u8
世界地理是指CCTV世界地理吗？

**Comment by SuperBlackWednesday** [comment]
http://www.tvsbar.com/hktv/1563.html    以前是看这个网站  都很经典 但是现在都看不了了
再求东森戏剧  还有东森洋片 感觉这几个台能组成个小型的奈菲   都是华语的 带版权的  播放的剧集单独搜索是没资源的
感谢

**Comment by SuperBlackWednesday** [comment]
这个东森电影HD好卡啊  以前有个大神分享的东森电影  不是HD的  那个不卡 就是不太清晰

**Comment by fanmingming** [comment]
国家地理 http://grogi.online:80/live/localSkypFr1220/localSkypFr1220/69316.ts
东森戏剧 http://123.51.230.108:18538/.m3u8
http://162.19.247.76:22222/live/dsxj/index.m3u8
http://61.221.81.93:8078/hls/34/80/ebcdrama.m3u8
东森洋片 http://162.19.247.76:22222/live/dsypt/index.m3u8
http://120.84.96.113:808/hls/33/index.m3u8
http://192.154.103.75:8080/ZZ_dongsenyangpian/ZZ_dongsenyangpian.m3u8

**Comment by SuperBlackWednesday** [comment]
哈哈  十分感谢大神 洋片和戏剧都很牛逼    就差东森电影了  这个源我就100K左右的速度  特别卡  我们俩应该不是一个线路
还能找到其他的源码？

**Comment by fanmingming** [comment]
暂时没有了，我先关闭Issues了。
