### ISSUE TITLE
IPv4 访问

### ISSUE THREAD

**Issue by MMmiaolege** [fanmingming/live#292]
抱歉喵，之前是因为校园网不支持 IPv6 而导致几乎全部频道失效... 不过 readme.md 里写着支持 IPv4 嘛，那请问 IPv4 直播源在哪里呢？

范明明 yyds！

**Comment by fanmingming** [comment]
IPv4源已停止提供。

**Comment by MMmiaolege** [comment]
> IPv4源已停止提供。

啊啊啊啊那那... 好吧喵，不过你至少要把 IPv4 从 readme 里删掉啊！

那、那我就用 Cloudflare 的 WARP（）

**Comment by fanmingming** [comment]
> > IPv4源已停止提供。
> 
> 啊啊啊啊那那... 好吧喵，不过你至少要把 IPv4 从 readme 里删掉啊！
> 
> 那、那我就用 Cloudflare 的 WARP（）

项目提供的所有资源都是支持双栈访问的，并不违背项目标题的描述。

**Comment by MMmiaolege** [comment]
> 项目提供的所有资源都是支持双栈访问的，并不违背项目标题的描述。

请问双栈是什么意思？我这不开 IPv6 就访问不了，连接 IPv6 就可以了。

**Comment by fanmingming** [comment]
![Uploading IMG_3688.jpeg…]()

**Comment by fanmingming** [comment]
![IMG_3688](https://github.com/fanmingming/live/assets/4993993/d3c960ce-41c9-4e47-8b14-b00e67991de2)

**Comment by MMmiaolege** [comment]
啊这... 我的意思是说：直播源使用 IPv4 访问？

**Comment by fanmingming** [comment]
抱歉，直播频道的资源并非是本项目可控的内容，项目只保证提供的静态资源支持双栈访问，而不是直播频道。

> 啊这... 我的意思是说：直播源使用 IPv4 访问？

**Comment by MMmiaolege** [comment]
呐好吧... 不过还是谢谢喵，感谢你对 IPTV 做出的贡献喵
