### ISSUE TITLE
电台语句判断错误

### ISSUE THREAD

**Issue by Justin9258** [fanmingming/live#293]
电台判断语句的ture应无双引号 
radio=true
否则无法被kodi识别

**Comment by fanmingming** [comment]
麻烦问下使用的是哪个源？
radio/m3u/index.m3u吗？

**Comment by Justin9258** [comment]
radio/m3u/index.m3u
radio/m3u/fm.m3u
两个都是


范明明 ***@***.***>于2024年5月14日 周二21:25写道：

**Comment by fanmingming** [comment]
已去除radio标签。
