### ISSUE TITLE
增加 EPG

### ISSUE THREAD

**Issue by iqingzhou** [fanmingming/live#3]
在网上看到的一些 EPG 信息，不知道能不能加进去？

1、51zmt.top

提供EPG的频道列表，每日与EPG同步更新

节目总表地址：http://epg.51zmt.top:8000/e.xml 测试用节目表，点击此处下载（仅提供节目表，不提供节目源）

央视及各省卫视：http://epg.51zmt.top:8000/cc.xml

地方及数字付费：http://epg.51zmt.top:8000/difang.xml

DIYP接口：http://epg.51zmt.top:8000/api/diyp/

使用tvg-name匹配

http://epg.51zmt.top:8000/#:~:text=%E6%8F%90%E4%BE%9BEPG,name%E5%8C%B9%E9%85%8D

佛系维护,完全免费,无任何广告,数据仅供个人学习使用,禁止任何形式的商业用途!

2、112114.xyz

Diyp & 百川点击选择程序接口：https://epg.112114.xyz/status

超级直播 https://epg.112114.xyz/epginfo

Xml格式 https://epg.112114.xyz/pp.xml

https://epg.112114.xyz/pp.xml.gz

Bing每日图片 https://epg.112114.xyz/bingimg

3、HK

https://epg.pw/xmltv/epg_HK.xml

https://epg.pw/xmltv/epg_HK.xml.gz

4、TW

https://epg.pw/xmltv/epg_TW.xml

https://epg.pw/xmltv/epg_TW.xml.gz

**Comment by fanmingming** [comment]
感谢支持，已经在源内添加EPG。
