### ISSUE TITLE
直接safari 播放ipv6地址 只有声音 没有图像

### ISSUE THREAD

**Issue by 91xcode** [fanmingming/live#307]
## 遇到的问题	
为什么https://live.fanmingming.com/player/?vurl=ipv6地址 可以 我本地确不行呢 只有声音 没有图像。直接safari 播放ipv6地址 只有声音 没有图像

**Comment by fanmingming** [comment]
浏览器没有视频解码。

**Comment by 91xcode** [comment]
为什么[https://live.fanmingming.com/player/?vurl=ipv6地址](https://live.fanmingming.com/player/?vurl=ipv6%E5%9C%B0%E5%9D%80) 可以 我本地确不行呢 只有声音 没有图像。 你这边用hls 播放 我这边也不行 请问如何处理呢

**Comment by fanmingming** [comment]
浏览器限制，视频流的链接需要https协议，包括m3u8的ts切片也必须是https协议。你可以下载保存播放器源码，进行本地测试不会有https限制。
