### ISSUE TITLE
发现有一些频道失效了

### ISSUE THREAD

**Issue by wangbf007** [fanmingming/live#316]
## 遇到的问题	
1 央视组 除了“cctv16奥运频道”和”cctv4k超高清“两个频道能播放，其他都失效了，包括CHC的3个电影台也失效了(把chc电影频道也放在数字组比较合理?）。
2 卫视组 内蒙古卫视 宁夏卫视 西藏卫视 这3个频道失效了。
3 数字组 爱上4k 金鹰纪实 茶友频道 快乐垂钓 梨园频道 这5个频道失效了
4 CGTN组除了阿语频道，其余都失效了。
看到有时间的话，修复或剔除下谢谢！

**Comment by fanmingming** [comment]
感谢反馈，正在逐步修复中。
