### ISSUE TITLE
ijkplayer播放不了视频

### ISSUE THREAD

**Issue by zhoucarson** [fanmingming/live#32]
## 遇到的问题	
使用ijkplauer编译，已经集成openssl，音频ac3，mp2 ,mpeg4 有空看看吗

## 您使用的源
如：使用的是Global

## 有问题的频道名称
在此填写的频道名称。

## 错误日志
D/IJKMEDIA: IjkMediaPlayer_native_setup
D/IJKMEDIA: ffpipeline_create_from_android()
D/IJKMEDIA: ijkmp_set_inject_opaque(0x3292)
D/IJKMEDIA: ijkmp_set_inject_opaque()=void
D/IJKMEDIA: ijkmp_set_ijkio_inject_opaque(0x3292)
D/IJKMEDIA: ijkmp_set_ijkio_inject_opaque()=void
D/IJKMEDIA: ijkmp_android_set_mediacodec_select_callback()
D/IJKMEDIA: ffpipeline_set_mediacodec_select_callback
D/IJKMEDIA: ijkmp_android_set_mediacodec_select_callback()=void
D/IJKMEDIA: IjkMediaPlayer_native_setLogLevel(8)
D/IJKMEDIA: moncleanup
D/IJKMEDIA: IjkMediaPlayer_setOptionLong
D/IJKMEDIA: IjkMediaPlayer_setLoopCount
D/IJKMEDIA: IjkMediaPlayer_setVolume
D/IJKMEDIA: ijkmp_android_set_volume(1.000000, 1.000000)
D/IJKMEDIA: ffpipeline_set_volume
D/IJKMEDIA: ijkmp_android_set_volume(1.000000, 1.000000)=void
D/IJKMEDIA: IjkMediaPlayer_setOptionLong
I/chatty: uid=10370(big.wan.top) identical 9 lines
D/IJKMEDIA: IjkMediaPlayer_setOptionLong
D/tv.danmaku.ijk.media.player.IjkMediaPlayer: Couldn't open file on client side, trying server side
D/IJKMEDIA: IjkMediaPlayer_setDataSourceAndHeaders
V/IJKMEDIA: setDataSource: path http://cntv.sbs/live?id=cctv1
D/IJKMEDIA: ijkmp_set_data_source(url="http://cntv.sbs/live?id=cctv1")
D/IJKMEDIA: ijkmp_set_data_source(url="http://cntv.sbs/live?id=cctv1")=0
D/IJKMEDIA: IjkMediaPlayer_prepareAsync
D/IJKMEDIA: ijkmp_prepare_async()
I/IJKMEDIA: SDL_RunThread: [21499] ff_msg_loop
D/IJKMEDIA: message_loop
D/IJKMEDIA: FFP_MSG_FLUSH:
D/IJKMEDIA: ijkmp_prepare_async()=0
I/IJKMEDIA: SDL_RunThread: [21500] ff_vout
I/IJKMEDIA: SDL_RunThread: [21501] ff_read
I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 1
I/TouchFilterInputStageHelper: [needTouchEventFilter] Displayid : 0
D/HandGripFilter: getdisplaysize, x : 1080 y : 2460
W/SQLiteLog: (28) double-quoted string literal: "A436F16DF16B0161DA5C94B5CBFFE4E1"
W/SQLiteLog: (28) double-quoted string literal: ""
W/SQLiteLog: (28) double-quoted string literal: "A436F16DF16B0161DA5C94B5CBFFE4E1"
W/SQLiteLog: (28) double-quoted string literal: "-1"
I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 131073
D/TextureView: getHardwareLayer, createNewSurface:true
D/IJKMEDIA: IjkMediaPlayer_setVideoSurface
D/IJKMEDIA: ijkmp_set_android_surface(surface=0x7fcd2cfec8)
D/IJKMEDIA: ffpipeline_set_surface()
D/IJKMEDIA: ijkmp_set_android_surface(surface=0x7fcd2cfec8)=void
I/Timeline: Timeline: Activity_idle id: ActivityRecord{643d86f token=android.os.BinderProxy@2cb653 {big.wan.top/big.wan.top.main.live.LivePlayerActivity}} time:2164399541
I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 131074
I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 2
I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [21501]
D/IJKMEDIA: FFP_MSG_ERROR: 0
E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)

**Comment by fanmingming** [comment]
排查你的设备的系统时间或者网络状态，先排除是否可以访问https链接。
如果可以访问，则可能是你的播放器或者设备内存不足导致的。
