### ISSUE TITLE
添加一些可用的高清直播链接，可以试试

### ISSUE THREAD

**Issue by lwr851** [fanmingming/live#321]
## 意见建议
请在此提出您的意见或建议。
#EXTINF:-1 tvg-name="四川新闻" tvg-logo="https://live.fanmingming.com/tv/四川新闻.png",group-title="四川卫视",四川新闻
http://110.189.102.15:9901/tsfile/live/0117_1.m3u8?key=txiptv&playlive=1&authid=0
#EXTINF:-1 tvg-name="四川新闻" tvg-logo="https://live.fanmingming.com/tv/四川新闻.png",group-title="四川卫视",四川新闻
http://wouu.net:9977/udp/239.93.0.47:5140
#EXTINF:-1 tvg-name="四川经济" tvg-logo="https://live.fanmingming.com/tv/四川经济.png",group-title="四川卫视",四川经济
http://wouu.net:9977/udp/239.93.1.101:5140
#EXTINF:-1 tvg-name="四川乡村" tvg-logo="https://live.fanmingming.com/tv/四川乡村.png",group-title="四川卫视",四川乡村
http://wouu.net:9977/udp/239.93.0.52:5140
#EXTINF:-1 tvg-name="四川科教" tvg-logo="https://live.fanmingming.com/tv/四川科教.png",group-title="四川卫视",四川科教
http://wouu.net:9977/udp/239.93.42.44:5140
#EXTINF:-1 tvg-name="四川文化旅游" tvg-logo="https://live.fanmingming.com/tv/四川文化旅游.png",group-title="四川卫视",四川文化旅游
http://wouu.net:9977/udp/239.93.1.102:5140
#EXTINF:-1 tvg-name="四川妇女儿童" tvg-logo="https://live.fanmingming.com/tv/四川妇女儿童.png",group-title="四川卫视",四川妇女儿童
http://wouu.net:9977/udp/239.93.0.219:5140
#EXTINF:-1 tvg-name="四川影视文艺" tvg-logo="https://live.fanmingming.com/tv/四川影视文艺.png",group-title="四川卫视",四川影视文艺
http://110.189.102.15:9901/tsfile/live/0137_1.m3u8?key=txiptv&playlive=1&authid=0
#EXTINF:-1 tvg-name="四川影视文艺" tvg-logo="https://live.fanmingming.com/tv/四川影视文艺.png",group-title="四川卫视",四川影视文艺
http://wouu.net:9977/udp/239.93.0.166:5140
#EXTINF:-1 tvg-name="四川峨眉电影" tvg-logo="https://live.fanmingming.com/tv/四川峨眉电影.png",group-title="四川卫视",四川峨眉电影
http://110.189.102.15:9901/tsfile/live/0118_1.m3u8?key=txiptv&playlive=1&authid=0
#EXTINF:-1 tvg-name="四川峨眉电影" tvg-logo="https://live.fanmingming.com/tv/四川峨眉电影.png",group-title="四川卫视",四川峨眉电影
http://wouu.net:9977/udp/239.93.0.252:5140

#EXTINF:-1 tvg-name="世界地理" tvg-logo="https://live.fanmingming.com/tv/世界地理.png",group-title="央视数字",世界地理
http://123.184.28.33/hlslive-tx-cdn.ysp.cctv.cn/469/2024172003.m3u8
#EXTINF:-1 tvg-name="世界地理" tvg-logo="https://live.fanmingming.com/tv/世界地理.png",group-title="央视数字",世界地理
http://180.137.22.80:8181/tsfile/live/1104_1.m3u8?key=txiptv&playlive=1&authid=0
#EXTINF:-1 tvg-name="世界地理" tvg-logo="https://live.fanmingming.com/tv/世界地理.png",group-title="央视数字",世界地理
http://222.90.31.220:8899/rtp/239.111.205.71:5140
#EXTINF:-1 tvg-name="兵器科技" tvg-logo="https://live.fanmingming.com/tv/兵器科技.png",group-title="央视数字",兵器科技
http://123.184.28.33/hlslive-tx-cdn.ysp.cctv.cn/476/2024172103.m3u8
#EXTINF:-1 tvg-name="兵器科技" tvg-logo="https://live.fanmingming.com/tv/兵器科技.png",group-title="央视数字",兵器科技
http://180.137.22.80:8181/tsfile/live/1098_1.m3u8?key=txiptv&playlive=1&authid=0
#EXTINF:-1 tvg-name="兵器科技" tvg-logo="https://live.fanmingming.com/tv/兵器科技.png",group-title="央视数字",兵器科技
http://222.90.31.220:8899/rtp/239.111.205.74:5140
#EXTINF:-1 tvg-name="第一剧场" tvg-logo="https://live.fanmingming.com/tv/第一剧场.png",group-title="央视数字",第一剧场
http://123.184.28.33/hlslive-tx-cdn.ysp.cctv.cn/048/2024171803.m3u8
#EXTINF:-1 tvg-name="第一剧场" tvg-logo="https://live.fanmingming.com/tv/第一剧场.png",group-title="央视数字",第一剧场
http://180.137.22.80:8181/tsfile/live/1108_1.m3u8?key=txiptv&playlive=1&authid=0
#EXTINF:-1 tvg-name="第一剧场" tvg-logo="https://live.fanmingming.com/tv/第一剧场.png",group-title="央视数字",第一剧场
http://222.90.31.220:8899/rtp/239.111.205.65:5140
#EXTINF:-1 tvg-name="怀旧剧场" tvg-logo="https://live.fanmingming.com/tv/怀旧剧场.png",group-title="央视数字",怀旧剧场
http://123.184.28.33/hlslive-tx-cdn.ysp.cctv.cn/114/2024171903.m3u8
#EXTINF:-1 tvg-name="怀旧剧场" tvg-logo="https://live.fanmingming.com/tv/怀旧剧场.png",group-title="央视数字",怀旧剧场
http://222.90.31.220:8899/rtp/239.111.205.67:5140
#EXTINF:-1 tvg-name="风云剧场" tvg-logo="https://live.fanmingming.com/tv/风云剧场.png",group-title="央视数字",风云剧场
http://123.184.28.33/hlslive-tx-cdn.ysp.cctv.cn/525/2024171703.m3u8
#EXTINF:-1 tvg-name="风云剧场" tvg-logo="https://live.fanmingming.com/tv/风云剧场.png",group-title="央视数字",风云剧场
http://222.90.31.220:8899/rtp/239.111.205.66:5140
#EXTINF:-1 tvg-name="风云音乐" tvg-logo="https://live.fanmingming.com/tv/风云音乐.png",group-title="央视数字",风云音乐
http://123.184.28.33/hlslive-tx-cdn.ysp.cctv.cn/252/2024163303.m3u8
#EXTINF:-1 tvg-name="风云音乐" tvg-logo="https://live.fanmingming.com/tv/风云音乐.png",group-title="央视数字",风云音乐
http://222.90.31.220:8899/rtp/239.111.205.69:5140
#EXTINF:-1 tvg-name="风云足球" tvg-logo="https://live.fanmingming.com/tv/风云足球.png",group-title="央视数字",风云足球
http://123.184.28.33/hlslive-tx-cdn.ysp.cctv.cn/161/2012514203.m3u8
#EXTINF:-1 tvg-name="风云足球" tvg-logo="https://live.fanmingming.com/tv/风云足球.png",group-title="央视数字",风云足球
http://180.137.22.80:8181/tsfile/live/1100_1.m3u8?key=txiptv&playlive=1&authid=0
#EXTINF:-1 tvg-name="风云足球" tvg-logo="https://live.fanmingming.com/tv/风云足球.png",group-title="央视数字",风云足球
http://222.90.31.220:8899/rtp/239.111.205.68:5140
#EXTINF:-1 tvg-name="高尔网球" tvg-logo="https://live.fanmingming.com/tv/高尔夫网球.png",group-title="央视数字",高尔网球
http://123.184.28.33/hlslive-tx-cdn.ysp.cctv.cn/469/2024166203.m3u8
#EXTINF:-1 tvg-name="高尔网球" tvg-logo="https://live.fanmingming.com/tv/高尔夫网球.png",group-title="央视数字",高尔网球
http://222.90.31.220:8899/rtp/239.111.205.73:5140
#EXTINF:-1 tvg-name="央视台球" tvg-logo="https://live.fanmingming.com/tv/央视台球.png",group-title="央视数字",央视台球
http://123.184.28.33/hlslive-tx-cdn.ysp.cctv.cn/320/2024172403.m3u8
#EXTINF:-1 tvg-name="央视台球" tvg-logo="https://live.fanmingming.com/tv/央视台球.png",group-title="央视数字",央视台球
http://222.90.31.220:8899/rtp/239.111.205.70:5140
#EXTINF:-1 tvg-name="电视指南" tvg-logo="https://live.fanmingming.com/tv/电视指南.png",group-title="央视数字",电视指南
http://123.184.28.33/hlslive-tx-cdn.ysp.cctv.cn/699/2024172503.m3u8
#EXTINF:-1 tvg-name="电视指南" tvg-logo="https://live.fanmingming.com/tv/电视指南.png",group-title="央视数字",电视指南
http://180.137.22.80:8181/tsfile/live/1099_1.m3u8?key=txiptv&playlive=1&authid=0
#EXTINF:-1 tvg-name="电视指南" tvg-logo="https://live.fanmingming.com/tv/电视指南.png",group-title="央视数字",电视指南
http://110.178.52.111:8085/udp/239.1.1.90:8090
#EXTINF:-1 tvg-name="女性时尚" tvg-logo="https://live.fanmingming.com/tv/女性时尚.png",group-title="央视数字",女性时尚
http://123.184.28.33/hlslive-tx-cdn.ysp.cctv.cn/440/2024172203.m3u8
#EXTINF:-1 tvg-name="女性时尚" tvg-logo="https://live.fanmingming.com/tv/女性时尚.png",group-title="央视数字",女性时尚
http://222.90.31.220:8899/rtp/239.111.205.72:5140
#EXTINF:-1 tvg-name="文化精品" tvg-logo="https://live.fanmingming.com/tv/文化精品.png",group-title="央视数字",文化精品
http://123.184.28.33/hlslive-tx-cdn.ysp.cctv.cn/370/2024172303.m3u8
#EXTINF:-1 tvg-name="文化精品" tvg-logo="https://live.fanmingming.com/tv/文化精品.png",group-title="央视数字",文化精品
http://222.90.31.220:8899/rtp/239.111.205.75:5140

#EXTINF:-1 tvg-name="CHC家庭影院" tvg-logo="https://live.fanmingming.com/tv/CHC家庭影院.png",group-title="央视数字",CHC家庭影院
http://110.189.102.15:9901/tsfile/live/0109_1.m3u8?key=txiptv&playlive=1&authid=0
#EXTINF:-1 tvg-name="CHC家庭影院" tvg-logo="https://live.fanmingming.com/tv/CHC家庭影院.png",group-title="央视数字",CHC家庭影院
http://222.90.31.220:8899/rtp/239.112.205.205:5140

#EXTINF:-1 tvg-name="CHC影迷电影" tvg-logo="https://live.fanmingming.com/tv/CHC影迷电影.png",group-title="央视数字",CHC影迷电影
http://180.137.22.80:8181/tsfile/live/1067_1.m3u8?key=txiptv&playlive=1&authid=0
#EXTINF:-1 tvg-name="CHC影迷电影" tvg-logo="https://live.fanmingming.com/tv/CHC影迷电影.png",group-title="央视数字",CHC影迷电影
http://222.90.31.220:8899/rtp/239.112.205.206:5140

#EXTINF:-1 tvg-name="CHC动作电影" tvg-logo="https://live.fanmingming.com/tv/CHC动作电影.png",group-title="央视数字",CHC动作电影
http://222.90.31.220:8899/rtp/239.112.205.207:5140

#EXTINF:-1 tvg-name="全球大片" tvg-logo="https://live.fanmingming.com/tv/全球大片.png",group-title="央视数字",全球大片
http://wouu.net:9977/udp/239.93.0.105:5140
#EXTINF:-1 tvg-name="热门剧场" tvg-logo="https://live.fanmingming.com/tv/热门剧场.png",group-title="央视数字",热门剧场
http://wouu.net:9977/udp/239.93.0.140:5140
#EXTINF:-1 tvg-name="谍战剧场" tvg-logo="https://live.fanmingming.com/tv/谍战剧场.png",group-title="央视数字",谍战剧场
http://wouu.net:9977/udp/239.93.0.95:5140

**Comment by fanmingming** [comment]
基于稳定性考虑会对频道做增减。
