### ISSUE TITLE
希望恢复凤凰系列节目

### ISSUE THREAD

**Issue by JerryXu09** [fanmingming/live#325]
## 遇到的问题	
最近发现凤凰卫视系列节目消失了，请问是有关源失效了，暂时没有源，还是因为其他原因不会再有凤凰系列了？

**Comment by fanmingming** [comment]
有1080p的IPv4源，放出来可能会把整套玩没了。暂时不添加了。

**Comment by JerryXu09** [comment]
好吧，坐等到时候更新别的凤凰源👍
