### ISSUE TITLE
求e.xml里面能更新T和T+1的数据

### ISSUE THREAD

**Issue by kxxwang** [fanmingming/live#328]
求e.xml里面能更新T和T+1的数据，不然每到凌晨就会有一段时间的空窗期。

http://epg.51zmt.top:8000/api/i/?ch=%E7%8E%AF%E7%90%83%E5%A5%87%E8%A7%82&date=2024-09-03

**Comment by fanmingming** [comment]
感谢反馈，目前提供的EPG信息e.xml数据来源于112114，考虑到巨大的流量以及用户客户端加载数据的使用体验，目前暂时只提供当天的EPG内容。后面可能会变更为通过.gz的方式提供更为详尽的EPG内容，前提是在保障用户可以正常获取完整EPG内容的情况下进行改进，因为Github对单个文件有限制或者CloudFlare提供的免费流量限制等因素，这个问题一直在考量当中，也非常感谢您的建议。

**Comment by kxxwang** [comment]
是不是可以把e.xml的内容进行精简，毕竟很多频道其实在m3u文件里面是没有的，这样同时满足t和t+1应该比当前的文件会小很多。至于成本问题如果不介意可以一起承担，哈哈。

**Comment by fanmingming** [comment]
> 是不是可以把e.xml的内容进行精简，毕竟很多频道其实在m3u文件里面是没有的，这样同时满足t和t+1应该比当前的文件会小很多。至于成本问题如果不介意可以一起承担，哈哈。

您的建议很好。目前项目所有静态资源和访问服务均为Github、CloudFlare或Vercel等服务商提供的免费服务。暂时没有自建EPG服务的打算。在看到您提问的当天，已经加入了51zmt的T+1内容分发，您可以手动使用https://live.fanmingming.com/e.xml.gz (数据来源自51zmt)或者可以使用其他作者的EPG。
