### ISSUE TITLE
关于demo.m3u和ivp6.m3u的疑问

### ISSUE THREAD

**Issue by grdws** [fanmingming/live#333]
你好
demo.m3u的第一行是这样的：
CGTN阿语#EXTM3U x-tvg-url="https://live.fanmingming.com/e.xml"
这行开始部分的“CGTN阿语”是有意放在此处发挥作用的吗？

使用ipv6.m3u作为直播源看电视节目，最近一些天白天都好，每晚21点左右开始，里面ipv6的源总是很卡，ipv4源不卡。这是什么原因，有办法避免没有？

**Comment by fanmingming** [comment]
感谢提醒，demo.m3u第一行是一个错误，目前已经修复这个问题。
您提到ipv6晚上卡顿的问题，可能是源服务器带宽问题或运营商在晚高峰会对ipv6流量做了限制。

**Comment by grdws** [comment]
近期ipv6源晚上卡顿，我估计是源服务器带宽问题，他们不应该对ipv6流量做什么限制。

**Comment by ixbcqq** [comment]
> 近期ipv6源晚上卡顿，我估计是源服务器带宽问题，他们不应该对ipv6流量做什么限制。 我一直在用你这个ipv6电视直播源，很长一段时间里有适时的维护。而且我看到有几个地方也在实时复制你的这个源。感谢你对众人做出的辛劳。

 某些地方的宽带运营商故意限制的
