### ISSUE TITLE
晴彩系列新频道

### ISSUE THREAD

**Issue by missyoubye** [fanmingming/live#335]
黑龙江 北京 重庆陆续上线晴彩系列新频道，包括晴彩竞技 晴彩篮球 晴彩青少 晴彩羽毛球，往大佬加入这几个频道logo，辛苦了
![Uploading Screenshot_2024-09-12-05-55-22-826_studio.scillarium.ottnavigator.jpg…]()

**Comment by missyoubye** [comment]
![IMG_20240913_130201](https://github.com/user-attachments/assets/526e4d98-e3de-4504-b724-d3a96278e0cd)
![IMG_20240913_132620](https://github.com/user-attachments/assets/c3322021-d2cc-43e5-a0eb-2303d74ae852)
![IMG_20240913_130225](https://github.com/user-attachments/assets/bc91fe78-f234-486f-af28-7b683d9e15bc)
![IMG_20240913_130116](https://github.com/user-attachments/assets/f748921b-08bc-4695-aad2-37dc15d6025e)
目前能接收到的四个频道，我也是屏幕截图。

**Comment by missyoubye** [comment]
晴彩羽毛球暂未上线貌似

**Comment by fanmingming** [comment]
感谢您的提供，节后会做更新。

**Comment by fanmingming** [comment]
抱歉回复并解决该问题晚了一些时间，目前已新增晴彩4个频道的节目Logo。感谢您的支持！
