### ISSUE TITLE
是否可以增加上海教育电视台？

### ISSUE THREAD

**Issue by WoKee** [fanmingming/live#338]
## 遇到的问题	
开学季，学校有很多要求看直播节目的需求，在上海教育电视台播出。 希望能加一下。

**Comment by grdws** [comment]
http://117.161.12.124/live/program/live/setvhd/8000000/mnf.m3u8
上海教育电视台，你可以自己加上。

**Comment by WoKee** [comment]
> http://117.161.12.124/live/program/live/setvhd/8000000/mnf.m3u8 上海教育电视台，你可以自己加上。

这是ipv4的吧。不知道支不支持ipv6？ 如果放到任务里，应该能自动更新失效链接吧

**Comment by grdws** [comment]
ipv4被更大范围的支持。

**Comment by fanmingming** [comment]
抱歉，目前暂无可稳定使用的该频道节目源。还请您访问上海教育电视台官网进行观看 https://www.setv.sh.cn/#/tvshow
