### ISSUE TITLE
海外都访问不了是吗？

### ISSUE THREAD

**Issue by trigsoft** [fanmingming/live#340]
## 遇到的问题	
请在此描述您遇到的问题。

**Comment by fanmingming** [comment]
抱歉啊，域名出了点问题。已经联系CloudFlare发工单了，可以将暂时可以将live.fanmingming.com替换成live.fanmingming.cn来替代。

**Comment by trigsoft** [comment]
我想问的是所有频道都连不上，m3u是可以下下来的，但是频道是不是海外不行

**Comment by fanmingming** [comment]
抱歉！部分频道可能会对地域有使用限制，这取决于源服务商的一些策略，直播节目的源都来自第三方，项目无法保证其在特殊网络环境下的有效性。

**Comment by trigsoft** [comment]
没问题，就是确认下。谢谢。
