### ISSUE TITLE
突然用不了了，人在海外

### ISSUE THREAD

**Issue by JoeyChen027** [fanmingming/live#341]
之前您的源一直用的很稳定，但是几天前突然连不上了，一直到现在，人在国外，是被墙了嘛？

**Comment by liqiangsky** [comment]
> 之前您的源一直用的很稳定，但是几天前突然连不上了，一直到现在，人在国外，是被墙了嘛？

你用的是m3u转txt格式的那个地址吗，那个大佬说出了些问题要等等，着急你可以自己转一下格式

**Comment by fanmingming** [comment]
cloudflare的反爬虫会返回403结果，您在海外建议m3u链接使用raw地址来订阅。

**Comment by JoeyChen027** [comment]
我一直用的raw地址，最近的是这个，没错吧？还请大神指点https://raw.githubusercontent.com/fanmingming/live/refs/heads/main/tv/m3u/ipv6.m3u
