### ISSUE TITLE
您好，通过xteve访问 403

### ISSUE THREAD

**Issue by lk6607** [fanmingming/live#346]
## 遇到的问题	
请在此描述您遇到的问题。
![111](https://github.com/user-attachments/assets/4043011a-fb76-44c0-b9d3-410275ca4b40)
是因为访问太频繁了吗？ 有没有办法放出来。

**Comment by fanmingming** [comment]
感谢反馈。该问题可能是Cloudflare防护导致的，目前已修复。请您再观察是否还有类似问题，如有问题欢迎继续反馈。
