### ISSUE TITLE
TXT转M3U格式的工具能否添加API接口？

### ISSUE THREAD

**Issue by Iensuredit** [fanmingming/live#348]
## 意见建议
感谢大佬的项目及维护，辛苦了！
能否为TXT转M3U工具增加API接口，以便将此类源直接添加至emby中？
再次感谢！

**Comment by fanmingming** [comment]
感谢您的建议，鉴于txt源的频道名称命名没有统一规范的标准，转换后的m3u可能存在大量的png路径404问题。所以，目前仅提供线上转换，以方便对不存在的频道logo加以手工修正。再次感谢！
