### ISSUE TITLE
我是小白我不会用，哪个是这个直播的链接？是直接复制最上面的网址 粘贴到电视TV上吗？

### ISSUE THREAD

**Issue by sd252457109** [fanmingming/live#349]
## 遇到的问题	
请在此描述您遇到的问题。

![1728725271180](https://github.com/user-attachments/assets/b0f76a02-d658-4912-b933-0f1745835dec)

**Comment by wangdashuaige** [comment]
![image](https://github.com/user-attachments/assets/ebe3d61e-11bd-4075-9411-d7a4d3b61052)

**Comment by fanmingming** [comment]
感谢提问，demo.m3u是作为引用项目静态资源的演示而创建的，还请您认真阅读下README.md来了解具体的使用说明。
