### ISSUE TITLE
IPV6无法播放

### ISSUE THREAD

**Issue by woboo110** [fanmingming/live#35]
## 遇到的问题	
用的友窝，这几天突然无法播放了，格式变了？

## 您使用的源
IPv6

**Comment by fanmingming** [comment]
抱歉，我个人的网络环境(联通双栈v4/v6)下在Android设备客户端Kodi、iOS设备APTV和PC使用PotPlsyer测试均可正常播放。
使用IPv6源之前，请确保自己的IPv4/v6的双栈网络可以正常联网。
另外，近日部分Vercel服务的IP疑似在国内部分地区出现被墙状态，目前还不清楚问题在哪里。
可以先尝试手动指定自己的DNS服务观察下。如果还有问题，麻烦说明下你使用的设备以及客户端。感谢！
