### ISSUE TITLE
地区台

### ISSUE THREAD

**Issue by qwernx** [fanmingming/live#352]
## 意见建议
请在此提出您的意见或建议。
能增加一些河南部分地方台吗？
我找了一些河南地区的部分地方台。能加上去吗？
你看一下我的仓库: https://github.com/qwernx/iptv-/blob/main/henan/hn2.m3u

**Comment by fanmingming** [comment]
感谢建议，您提供链接当中的频道应该是运营商内网源。其他地区运营商的用户无法使用的。
