### ISSUE TITLE
有些频道失效了

### ISSUE THREAD

**Issue by wangbf007** [fanmingming/live#355]
1.凤凰卫视三个台最近是不是失效了?
2.央视CCTV2经济频道在电视上用地址订阅方式 播放不出 一直转圈圈?
但是下载m3u文件在电脑上能播放CCTV2
很奇怪的现象 我看了看央视的每个频道具体地址 除了央视2频道地址比较短和其他央视具体频道地址不一样 其他央视地址比较长且类似...
最后感谢一直以来的更新维护!!!

**Comment by starkong2022** [comment]
同样的问题，希望大佬维护一下

**Comment by opeopeopeopeopeopeopeopeopeopeopeopeope** [comment]
内测了一下，好像ipv6.m3u这个文件cctv2很正常
![屏幕截图 2024-10-26 150454](https://github.com/user-attachments/assets/2b7dded5-6450-4921-a691-d203bd3c1b17)
但是因为我使用的播放器是PotPlayer显示不删除台标

**Comment by starkong2022** [comment]
我是电视上TiviMate和手机mytv测试CCTV2不能播放![Screenshot_20241026_193826_com.lizongying.mytv0.jpg](https://github.com/user-attachments/assets/91267a21-67fa-4df9-9150-251d2f828ab6)

**Comment by lichunlin123** [comment]
求大佬维护一下凤凰卫视源
