### ISSUE TITLE
IPV4 直播源， 目前（2024 10 29）还可用吗？ 谢谢

### ISSUE THREAD

**Issue by sshuangliu** [fanmingming/live#358]
## 遇到的问题	
请在此描述您遇到的问题。

**Comment by zd200237** [comment]
我用不成。

**Comment by fanmingming** [comment]
项目未提供IPv4直播源。

**Comment by feng720506** [comment]
正常使用。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年11月4日(周一) 下午5:17
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [fanmingming/live] IPV4 直播源， 目前（2024 10 29）还可用吗？ 谢谢 (Issue #358)




 
Closed #358 as completed.
