### ISSUE TITLE
播放卡顿

### ISSUE THREAD

**Issue by Yea8m** [fanmingming/live#359]
## 遇到的问题	
请在此描述您遇到的问题。
播放卡顿是链接被墙了吗？

**Comment by whybm** [comment]
联通网络，同样的问题，所有频道基本都不能正常播放了

**Comment by swxk521** [comment]
移动网络，卡顿

**Comment by whybm** [comment]
已经恢复正常

**Comment by boge-github** [comment]
> 移动网络，卡顿

一样，难道不支持移动的了。以前一直好好的

**Comment by whybm** [comment]
联通网络所有频道基本都不能正常播放，电信网络一切正常

可能是限ip了，奇怪的是，看直播地址是黑龙江移动的，但是电信的网络却能看

希望能更换成通用的直播地址

**Comment by fanmingming** [comment]
目前还在观察。预计周日会更新，最晚周一会补全所有频道。
