### ISSUE TITLE
TVBOX takagen99版本无法加载此m3u

### ISSUE THREAD

**Issue by JoeryLee** [fanmingming/live#36]
## 遇到的问题	
TVBOX takagen99版本无法加载此m3u，提示频道列表为空

## 您使用的源
Global.m3u

kodi也无法加载，只有potplayer可以用。

**Comment by fanmingming** [comment]
感谢您反馈问题。
关于tvbox的问题请咨询该应用作者。
kodi经本地测试目前可正常使用。
添加m3u链接请使用live开头的域名链接，鉴于每个人较为复杂的网络环境原因，不建议使用GitHub的raw链接来订阅m3u源或使用带有前置代理域名的raw链接来添加订阅，因为访问live域名的内容是由GitHub完全托管并构建的。最后还请先检查链接是否输入正确或完整。
排除以上问题后，检查是否可以正常访问https://live.fanmingming.com 。
如有问题，欢迎继续提出反馈。
