### ISSUE TITLE
连接错误

### ISSUE THREAD

**Issue by czyzx** [fanmingming/live#363]
大佬  报这个错误是啥原因呀？
error code io network connection failed 2001

**Comment by czyzx** [comment]
![image](https://github.com/user-attachments/assets/ba8120ec-0b30-4932-a8b7-a808fa78280e)
使用vlc测试 报这个错误

**Comment by czyzx** [comment]
请问是不是这个IP被运营商封掉了呀？

**Comment by fanmingming** [comment]
请先确保设备可以访问公网IPv6地址，再来使用。
