### ISSUE TITLE
ipv6直播源

### ISSUE THREAD

**Issue by jamesjiangwx** [fanmingming/live#364]
范先生，您好！
我看到你把ipv6电视直播源更新了，现在那里面的频道都能看了，不过怎么没有香港凤凰卫视了呢？还能想办法加进去吗？
谢谢，James.

**Comment by fanmingming** [comment]
感谢您提交问题，有可用的频道源会添加上来的。

**Comment by jamesjiangwx** [comment]
范总：

我是您电视直播源的忠实FANS，原来GITHUB网站上的IPV6直播源好像不好用了呢？ 您还有维护吗，或者文件挪到别的地方去了？

谢谢，James.




在 2024-11-11 16:09:24，"范明明" ***@***.***> 写道：

感谢您提交问题，有可用的频道源会添加上来的。
