### ISSUE TITLE
疑似很多台失效

### ISSUE THREAD

**Issue by chuwza** [fanmingming/live#365]
## 遇到的问题	
请在此描述您遇到的问题。

大佬好，不知道是我的问题还是确实失效了，浙江电信

实测CCTV1秒放出，但是其他很多台都放不出，例如CCTV5、CCTV5+、CCTV6、CCTV7、CCTV16等，
剩下不列举了，因为就没几个放得出的

**Comment by 1359099501** [comment]
我常州联通最近也不能放了，之前很流畅

**Comment by fanmingming** [comment]
非常抱歉啊，最近忙着考试的事情，后面会慢慢修复。

**Comment by chuwza** [comment]
> 非常抱歉啊，最近忙着考试的事情，后面会慢慢修复。

好的，非常感谢

**Comment by jxwdgd5201314** [comment]
可以问下用的那个播放器吗？麻烦帮忙推荐下

**Comment by chuwza** [comment]
> 可以问下用的那个播放器吗？麻烦帮忙推荐下

https://t.me/mytv_android_release

这个，“mytv-android”（https://github.com/yaoxieyoulei/mytv-android）的分支：“天光云影”

**Comment by jxwdgd5201314** [comment]
多谢
