### ISSUE TITLE
一到晚高峰，很多台都放不出

### ISSUE THREAD

**Issue by chuwza** [fanmingming/live#368]
## 遇到的问题	
请在此描述您遇到的问题。
一到18:00左右晚高峰，央视很多台就放不出来，只有零星几个台比如卫视台、数字台可以放出来

但是过了晚高峰，比如在22:00这样，就又都正常了😂

你说节目源有问题吧，22:00的时候就很流畅，也全都放得出；你说节目源没问题吧，每次饭点就是放不出😭（我习惯吃饭的时候打开电视看）

有人有相同情况吗？是单纯我这边的问题（浙江电信），还是很多人都有这个问题？

**Comment by EastLord** [comment]
我也是这样

**Comment by chuwza** [comment]
> 我也是这样

感谢反馈，我看了一下APTV的tg群，破案了：IPv6用的人太多，已废🥲😂
![Screenshot_20241117-202624_Telegram](https://github.com/user-attachments/assets/85ce7eb5-f663-43c5-b0b5-f53589a8e99e)

**Comment by EastLord** [comment]
唉，这可咋整啊🥹

**Comment by chuwza** [comment]
> 唉，这可咋整啊🥹

非高峰期正常看，高峰期只能挑那些负载小的台看了，比如北京卫视😂

**Comment by bluetree2009** [comment]
我也是这样，最近几天比较严重。
