### ISSUE TITLE
很多频道音频源解析失败，显示声道数为0

### ISSUE THREAD

**Issue by jxwdgd5201314** [fanmingming/live#375]
## 遇到的问题	
请在此描述您遇到的问题。
如图
![image](https://github.com/user-attachments/assets/c724b0a9-10f3-4986-80ed-104f054ffeb6)
![image](https://github.com/user-attachments/assets/9ccd1ab1-d232-48fd-b9f7-073c06c24222)
![6ce15dac80a0e3df27f795d3ce62a76](https://github.com/user-attachments/assets/b2e2ca9b-b810-4010-abf4-81f18138b6e0)

**Comment by jxwdgd5201314** [comment]
有声音的频道。音频编码是aac,解码器aac,无声音频道音频编码是mp2,无解码器

**Comment by fanmingming** [comment]
您的问题是因为播放软件解码导致的，建议等待软件作者更新来修复或者更换其他播放器来使用。

**Comment by jxwdgd5201314** [comment]
多谢作者，您有推荐的播放器吗？
