### ISSUE TITLE
所有台都不能看了 ipv6

### ISSUE THREAD

**Issue by ghfangzong** [fanmingming/live#380]
## 遇到的问题	
请在此描述您遇到的问题。
所有台都是黑屏 播放错误 用的是ipv6的链接

**Comment by fanmingming** [comment]
感谢反馈，经测试可正常使用。请检查您的设备是否有IPv6网络接入。

**Comment by ghfangzong** [comment]
经测试源是好的 是我的播放软件有问题 我现在用的是mytv0  有没有什么好的播放软件能介绍一个 要简单的老人用 谢谢

**Comment by wjw020206** [comment]
> 经测试源是好的 是我的播放软件有问题 我现在用的是mytv0 有没有什么好的播放软件能介绍一个 要简单的老人用 谢谢

可以试试这个 https://github.com/yaoxieyoulei/mytv-android

这个操作简单，内置了 fanmingming 源（也可以自定义添加源)

**Comment by ghfangzong** [comment]
谢谢大佬

**Comment by wjw020206** [comment]
> 谢谢大佬

补充一点，建议使用图中红线圈出的版本，目前这个软件的最新版本有些问题(画面卡顿等)，实测这个版本的是比较稳定的
<img width="1321" alt="image" src="https://github.com/user-attachments/assets/de784cad-6a7a-46a1-9651-3bb572976c24" />

下载地址：https://github.com/yaoxieyoulei/mytv-android/releases/download/tv2.2.6/mytv-android-tv-2.2.6-all-sdk21-media3-1.3.1.apk

**Comment by ghfangzong** [comment]
感谢您的指导，现在已经用上了！

**Comment by wjw020206** [comment]
> 感谢您的指导，现在已经用上了！

坏消息：https://github.com/yaoxieyoulei/mytv-android 删库了，你安装包自己保留一下，不知道还能用多久

**Comment by bluetree2009** [comment]
> > 感谢您的指导，现在已经用上了！
> 
> 坏消息：https://github.com/yaoxieyoulei/mytv-android 删库了，你安装包自己保留一份，不知道还能用多久

帮忙提供一份下载文件吧， 没赶上车，谢谢

**Comment by wjw020206** [comment]
> > > 感谢您的指导，现在已经用上了！
> > 
> > 
> > 坏消息：https://github.com/yaoxieyoulei/mytv-android 删库了，你安装包自己保留一份，不知道还能用多久
> 
> 帮忙提供一份下载文件吧， 没赶上车，谢谢

邮箱给一个，我发你

**Comment by bluetree2009** [comment]
> > > > 感谢您的指导，现在已经用上了！
> > > 
> > > 
> > > 坏消息：https://github.com/yaoxieyoulei/mytv-android 删库了，你安装包自己保留一份，不知道还能用多久
> > 
> > 
> > 帮忙提供一份下载文件吧， 没赶上车，谢谢
> 
> 邮箱给一个，我发你

fengjuxiu@gmail.com

谢谢。
