### ISSUE TITLE
ipv6源失效。

### ISSUE THREAD

**Issue by sunday72840** [fanmingming/live#387]
## 遇到的问题	
请在此描述您遇到的问题。
ipv6的源抓取程序能否开源，可以使程序部署到本地使用？

**Comment by sln162** [comment]
> ## 遇到的问题
> 请在此描述您遇到的问题。 ipv6的源抓取程序能否开源，可以使程序部署到本地使用？

哪有抓取程序，每天都逛恩山，有新的源出来你也很快知道

**Comment by FlootingDream** [comment]
好像确实失效了

**Comment by ylq016** [comment]
> > ## 遇到的问题
> > 请在此描述您遇到的问题。 ipv6的源抓取程序能否开源，可以使程序部署到本地使用？
> 
> 哪有抓取程序，每天都逛恩山，有新的源出来你也很快知道

https://github.com/ssili126/tv

**Comment by alpsmonkey** [comment]
全村的希望破灭了

**Comment by bncolin** [comment]
> 全村的希望破灭了

https://github.com/fanmingming/live/issues/388#issuecomment-2556179992

**Comment by fanmingming** [comment]
由于不可抗力的原因，项目静态资源调用请将域名的com替换成cn。
