### ISSUE TITLE
部分直播源失效

### ISSUE THREAD

**Issue by yuhuan05** [fanmingming/live#395]
## 遇到的问题	
请在此描述您遇到的问题。
![image](https://github.com/user-attachments/assets/22e7cc30-fd32-47ef-8fb5-87ca0055f4c4)
部分直播源又失效了 麻烦大佬修复  感谢！！！

**Comment by oovipy** [comment]
＋1

**Comment by tedliu2024** [comment]
包含fanmingming的都被墙了

**Comment by MvBox** [comment]
同样

**Comment by cloudpanl** [comment]
我的也是，所有频道都看不了

**Comment by mr-chenwu** [comment]
为什么我都能看？你们确定不是捣乱的。看看自己的ipv6. 更新最新源文件。

**Comment by liyangzbx** [comment]
> 为什么我都能看？你们确定不是捣乱的。看看自己的ipv6. 更新最新源文件。

https://raw.githubusercontent.com/fanmingming/live/refs/heads/main/tv/m3u/ipv6.m3u，这个用tivimate就加载不出来，用ok影视可以载

**Comment by mr-chenwu** [comment]
很多人，都能上github，竟然还想伸手要饭吃，实在想不懂。

**Comment by yuhuan05** [comment]
> 很多人，都能上github，竟然还想伸手要饭吃，实在想不懂。

？？？这就是伸手要饭吃？？？你怕不是吃多了闲的没事干，在这显摆什么？

**Comment by yuhuan05** [comment]
> > 为什么我都能看？你们确定不是捣乱的。看看自己的ipv6. 更新最新源文件。
> 
> [https://raw.githubusercontent.com/fanmingming/live/refs/heads/main/tv/m3u/ipv6.m3u，这个用tivimate就加载不出来，用ok影视可以载](https://raw.githubusercontent.com/fanmingming/live/refs/heads/main/tv/m3u/ipv6.m3u%EF%BC%8C%E8%BF%99%E4%B8%AA%E7%94%A8tivimate%E5%B0%B1%E5%8A%A0%E8%BD%BD%E4%B8%8D%E5%87%BA%E6%9D%A5%EF%BC%8C%E7%94%A8ok%E5%BD%B1%E8%A7%86%E5%8F%AF%E4%BB%A5%E8%BD%BD)

你看看这个提交的时间没关而已叫啥
