### ISSUE TITLE
为啥这几天用不了呀？

### ISSUE THREAD

**Issue by xumeitian** [fanmingming/live#397]
## 遇到的问题	
请在此描述您遇到的问题。

**Comment by xumeitian** [comment]
直播源可以用，是我自己设置的问题。不好意思

**Comment by yanruodi1412** [comment]
> 直播源可以用，是我自己设置的问题。不好意思

能麻烦问一下设置问题是什么吗？最近我使用时也会有卡顿，想排查一下问题，谢谢。
