### ISSUE TITLE
有关播放卡顿的问题

### ISSUE THREAD

**Issue by Pauluooooo** [fanmingming/live#41]
## 遇到的问题	
刚开始打开时候速度很快，很流畅，播放几分钟，最长十多分钟之后就卡住了，下载速度直接没有了。
自己的网络是好的
使用的是 Windows 10 PotPlayer 客户端。

## 您使用的源
Global直播源

## 有问题的频道名称
CCTV 1 5 13 等，其他未一一测试

**Comment by fanmingming** [comment]
感谢支持。IPv4直播源到高峰时段确实存在这样的问题，很抱歉目前暂无法解决这个问题。建议使用ipv6源，可流畅观看节目。再次感谢！
