### ISSUE TITLE
foobar2000 打开 radio 的 m3u 中文乱码

### ISSUE THREAD

**Issue by dream7180** [fanmingming/live#42]
如题，是 foobar2000 只支持带 bom 的 UTF-8 所致，能否把 radio 的 m3u 改成 UTF-8 Bom，或者增加一个该编码的 m3u，谢谢！

**Comment by fanmingming** [comment]
好的，先忍一忍。明天安排。
感谢支持！

**Comment by dream7180** [comment]
十分感谢！

**Comment by fanmingming** [comment]
已经重新编码为UTF-8 with BOM格式。应该刷新下就好了。

**Comment by dream7180** [comment]
已集成到我的配置里 ：https://github.com/dream7180/foobox-cn/releases/tag/7.10
