### ISSUE TITLE
所有频道无法播放

### ISSUE THREAD

**Issue by netrfs** [fanmingming/live#43]
## 遇到的问题	
所有频道无法播放

## 您使用的源
如：ipv6

## 有问题的频道名称
所有频道

**Comment by fanmingming** [comment]
感谢。
经测试可正常使用。请先检查自己的网络环境是否支持ipv6，手机关闭Wi-Fi后如正常观看则可能是本地网络尚未开启ipv6或者本地ipv6的dns设置有误。访问https://www.test-ipv6.com/index.html.zh_CN 可对本地网络状态进行检测。
