### ISSUE TITLE
厦门卫视无法播放

### ISSUE THREAD

**Issue by CloudSVC** [fanmingming/live#46]
## 遇到的问题	
请在此描述您遇到的问题。
进不去，一直卡着，我用的是kodi的播放器
## 您使用的源
如：IPv6、Global或Radio
IPv6
## 有问题的频道名称
在此填写的频道名称。
厦门卫视

**Comment by fanmingming** [comment]
感谢反馈，可能是kodi播放器自身的bug。厦门卫视是标清规格的频道，经测试两个源当中的厦门卫视均可正常播放。

**Comment by CloudSVC** [comment]
> 感谢反馈，可能是kodi播放器自身的bug。厦门卫视是标清规格的频道，经测试两个源当中的厦门卫视均可正常播放。

好，我再看看，其他节点，像湖南卫视 CCTV 都是没问题的，就是厦门卫视进不去。😂
