### ISSUE TITLE
Global直播源只能播放几1分钟

### ISSUE THREAD

**Issue by vtgzhou** [fanmingming/live#47]
## 遇到的问题	
Global直播源只能播放几1分钟，用potplayer可以播放1分钟左右，用win10自带的播放器可以播放1、2十秒。

## 您使用的源
Global

## 有问题的频道名称
基本上都是同样的问题，如CCTV-1

**Comment by iOSleep** [comment]
自己用m3u8播放，测试链接只提供一分钟试看

**Comment by copurxia** [comment]
emby一样

**Comment by fanmingming** [comment]
感谢反馈，节目源来源于网络，受限于节目源服务提供商原因高峰期可能会存在卡顿。出现暂停播放的情况，请使用带有自动重连的播放器。目前，强烈推荐使用项目提供的ipv6源来观看节目。ipv4源播放的问题可能会在日后有所改善。
