### ISSUE TITLE
香港电视的源可以添加多点吗？大神，如翡翠台，无线新闻台、无线财经台、j2、vuitv等等

### ISSUE THREAD

**Issue by Penggzh1993** [fanmingming/live#49]
## 
Global

## 有问题的频道名称
在此填写的频道名称。

**Comment by fanmingming** [comment]
感谢支持，已经添加了您提到的部分频道。

**Comment by fanmingming** [comment]
非常抱歉，由于目前Github的Actions和Github Pages服务出现故障，已经更新的频道暂时无法刷新出来，Github方面已经做出说明大约几小时修复问题。详细情况可访问：https://status.github.com
