### ISSUE TITLE
Jellyfin 中导入重庆广电源没声音

### ISSUE THREAD

**Issue by mapleafgo** [fanmingming/live#5]
如题在 jellyfin 中导入重庆广电源没有声音，每个频道都是，且分辨率很低。我用VLC客户端试了下并没有这个问题，而且VLC中分辨率从640提升到了1920

**Comment by fanmingming** [comment]
感谢反馈，重庆广电的源是自适应播放的直播源，会根据设备或网速自动适配分辨率。
播放没有声音的问题，请检查播放应用设置的视频输出选项，如果当前是硬解码，可以尝试使用软解码，反之相同。
对于播放缓慢的问题，如果你的设备是通过代理访问网络，建议关闭代理后再试。

**Comment by mapleafgo** [comment]
这个自适应能通过什么方式欺骗吗，声音应该也跟这个有关

**Comment by fanmingming** [comment]
这个，我也不是很清楚。
没声音的问题，很大可能与播放设备的硬件或者播放器本身有关系。

**Comment by mapleafgo** [comment]
声音的问题，我不确定是哪里原因，但我用其他源时并没有这个问题。我这里是重庆，所以这个源速度很快，可这个问题却是难受。我再多试试吧，谢谢你的解答
