### ISSUE TITLE
403错误

### ISSUE THREAD

**Issue by zhaoxiao9302** [fanmingming/live#53]
## 遇到的问题	
在电视上使用tivimate播放，每次刚打开没有问题，但是播放不到1分钟，就开始转圈圈，然后显示403错误。
这难道是我家网络被对方加入黑名单了吗？可是为啥刚进入的时候就能看呢？

## 您使用的源
IPv6、Globa都存在。

## 有问题的频道名称
基本上每个频道。

感谢。

**Comment by fanmingming** [comment]
麻烦提供下Tivimate版本号。
测试过使用Tivimate官方正版没出现403错误的问题。

**Comment by zhaoxiao9302** [comment]
> 麻烦提供下Tivimate版本号。 测试过使用Tivimate官方正版没出现403错误的问题。

我用的2.8.0，不过之前是电脑上用potplayer播放也是一样的问题。
今天更新源了之后，暂时没有遇到403问题了。
谢谢。
