### ISSUE TITLE
Global直播源里的台湾测试无法直播

### ISSUE THREAD

**Issue by xibeilang0616** [fanmingming/live#54]
电视：康佳G65G10U，安卓8.0
网络：西安移动宽带1000兆，完美支持IPV6。
软件：Kodi 18.7(优点IPTV插件加载快）
问题：央视卫视直播正常，里面港台直播源无法播放，选择频道等待半天无反应。

**Comment by xibeilang0616** [comment]
> 电视：康佳G65G10U，安卓8.0 网络：西安移动宽带1000兆，完美支持IPV6。 软件：Kodi 18.7(优点IPTV插件加载快） 问题：央视卫视直播正常，里面港台直播源无法播放，选择频道等待半天无反应。

试验把kodi升级20.0，台湾测试频道恢复正常直播

**Comment by fanmingming** [comment]
部分频道失效已经去掉了。Android设备使用Tivimate测试均可正常播放。

**Comment by fanmingming** [comment]
由于服务器流量巨大。不得不下线台湾测试频道了。非常抱歉！

**Comment by xibeilang0616** [comment]
> 由于服务器流量巨大。不得不下线台湾测试频道了。非常抱歉！

太可惜了，作为国内用户对港澳台大部分不感兴趣，闲暇之余也就是看看湾湾蓝营、绿营阵营电视台的或温或激进台独状况。
IPV6专用直播源，响应速度快，画质稳定流畅无半点卡顿，给你们点赞👍👍👍
