### ISSUE TITLE
EPG能否提供过去一星期或者5天节目指南

### ISSUE THREAD

**Issue by lingbaoboy** [fanmingming/live#55]
## 意见建议
请在此提出您的意见或建议。

如题，目前的EPG只提供了当天的节目指南，我目前发现ipv6源应该室支持回看的，但是没有过去数天内的节目指南回看就不方便了。

我不太确定软件是否会缓存过去的节目源，比如ios的APTV，如果今天有打开过软件，明天再打开软件，那么今天的指南有可能还在，但是如果没打开过软件，那么可能就找不到前几天的指南了。

所以希望至少能实现过去1-3天的节目指南

**Comment by fanmingming** [comment]
首先，感谢支持。EPG内容实际上是112114的分发，由GitHub每小时自动更新并构建的。回看节目需要app将节目单缓存到本地，也就是每天（最好是晚间）打开一次播放器。如果您觉得不方便可以找下其他免费的epg来替代。再次感谢🙏
