### ISSUE TITLE
老大你好，想请问一下，用md文件怎么发步成网站，能指点一下吗？

### ISSUE THREAD

**Issue by vbskycn** [fanmingming/live#58]
老大，你好，我是一个新手。
一直在学习静态生成器，我主要是想生成单页面的，hugo,jekyll都比较多功能
我只要把一个README.md生成网站首页就可以了，就像你的  https://live.fanmingming.com/
用的是vercel拖管吗？

看了你的项目myphp
30秒在Vercel构建自己的无服务器php环境并实现国内直连访问。
这个很不错，但是就是不能构建一个只生成README.md的github网站
能够指点一下吗？谢谢了
jie@zhoujie.link

**Comment by fanmingming** [comment]
GitHub Pages可以托管静态内容，当开启GitHub Pages且根目录不存在index.html文件的时候readme就会自动成为首页。

**Comment by vbskycn** [comment]
谢谢
