### ISSUE TITLE
M3U只能拿到2-3段视频地址

### ISSUE THREAD

**Issue by 944095635** [fanmingming/live#59]
## 遇到的问题	
打开M3u文件，再点击CCTV1指向M3U8。每次下载下来内部有三个ts文件，播放我这三个文件视频就卡死了。

## 您使用的源
Global

**Comment by fanmingming** [comment]
目前IPv4是存在卡顿的问题，建议使用IPv6源来观看节目。
后续有更好用的直播源会做进一步改进。感谢支持！
