### ISSUE TITLE
最近更新的源大多数无法ipv6无法看

### ISSUE THREAD

**Issue by uncle-pier** [fanmingming/live#61]
## 遇到的问题	
今天更新的貌似大多数我这边用不了， 陕西 西安

## 您使用的源
IPv6

## 有问题的频道名称
大多数频道都不能正常来看，使用potplay

**Comment by fanmingming** [comment]
抱歉，原直播源链接路径进行了变更。添加了新的ipv6直播源，新源不能使用可通过下方链接继续使用原来的IPv6直播源https://live.fanmingming.com/tv/m3u/v6.m3u

**Comment by fanmingming** [comment]
修复了，抱歉。
