### ISSUE TITLE
cntv.sbs 这个域名好像解析不出来v6的地址

### ISSUE THREAD

**Issue by namebuhtig** [fanmingming/live#63]
cntv.sbs 这个域名好像解析不出来v6的地址 所以ipv6.m3u播放不出来

**Comment by fanmingming** [comment]
感谢反馈，Vercel确实没有IPv6解析，考虑到一般情况下有IPv6接入的设备都是双栈网络，为了便于后期维护做了更改。您可以继续使用原来的IPv6源，变更后的链接地址是https://live.fanmingming.vom/tv/m3u/v6.m3u
