### ISSUE TITLE
建议加戏剧直播

### ISSUE THREAD

**Issue by liqideqq** [fanmingming/live#66]
## 意见建议
我正在使用global.m3u文件，我的老人想观看戏曲直播，但我在几个直播平台上都没有找到戏曲直播。希望您能帮助我们添加一些戏曲直播的频道，非常感谢您的帮助。

**Comment by liqideqq** [comment]
> 谢谢，您有相关戏剧频道名称吗？ 目前使用环球源可以观看CCTV11和七彩戏剧频道。
河南电视台梨园频道

**Comment by fanmingming** [comment]
感谢您提交的问题，梨园频道已经加上了。后面有问题欢迎继续反馈。
