### ISSUE TITLE
频道的画面问题

### ISSUE THREAD

**Issue by liqideqq** [fanmingming/live#68]
## 遇到的问题	
有些频道的画面较窄，不完整。
## 您使用的源
Global
## 有问题的频道名称
内蒙古卫视
宁夏卫视
青海卫视
山西卫视
湖北卫视
厦门卫视
康巴卫视
新疆卫视
兵团卫视
西藏卫视
金鹰卡通
嘉佳卡通
财富天下
中国天气

**Comment by fanmingming** [comment]
感谢反馈，因为部分频道是4:3画面的源，建议拉伸到16:9进行观看。有HD和FHD资源的话后期会进一步改进。

**Comment by liqideqq** [comment]
好的，辛苦了
