### ISSUE TITLE
ipv6用不了

### ISSUE THREAD

**Issue by yingxiao6667** [fanmingming/live#69]
IPv6全部看不了，都超时，iOS端用的aptv 这个APP

**Comment by fanmingming** [comment]
感谢反馈，经测试可正常播放。
请访问https://www.test-ipv6.com/index.html.zh_CN 测试您的网络环境是否正常。如全部正常，请关闭VPN软件后再进行尝试。

**Comment by yingxiao6667** [comment]
![IMG_3910](https://github.com/fanmingming/live/assets/140678780/2198ebfa-8b5e-4454-94dc-f8f8a7f72ea1)
![IMG_3911](https://github.com/fanmingming/live/assets/140678780/4217bdb2-76cf-4714-a760-b8efd72255c9)

**Comment by fanmingming** [comment]
感谢，看到您截图当中CCTV3、6、7都有返回延迟数据，请在关闭VPN软件后点击进入频道再次尝试观看节目。
如果还无法正常观看节目，建议在蜂窝网络下进行测试。也可能是部分直播源对您的宽带运营商进行了屏蔽。
