### ISSUE TITLE
希望添加韩国购物频道的直播源

### ISSUE THREAD

**Issue by yidashi45678** [fanmingming/live#73]
希望添加韩国购物频道的直播源🤣🤣🤣🤣

**Comment by fanmingming** [comment]
感谢反馈，稍后会进一步完善。

**Comment by fanmingming** [comment]
可以提供下频道的官网地址吗或者完整的频道名称。谢谢！

**Comment by yidashi45678** [comment]
> 可以提供下频道的官网地址吗或者完整的频道名称。谢谢！

就是那种卖内衣卖丝袜的购物频道，哈哈哈 可以吗 给你赞助了

**Comment by fanmingming** [comment]
😓，没找到你说的频道。先关闭了。
