### ISSUE TITLE
fanmingming和友善的肥羊对比测评

### ISSUE THREAD

**Issue by xibeilang0616** [fanmingming/live#74]
友善肥羊的直播源是多而烂，画面卡顿、噎住家常便饭，黑屏失效的多，平均联通有效性只有40%

fanmingming的直播源是少而精，长时间段内直播画面极其稳定，很少见到失效黑屏转圈圈的直播源。

**Comment by fanmingming** [comment]
没必要对比的。最近请求量太大了，可能会超过vercel免费的100G流量阈值，怕是很快也会全部失效。😓

**Comment by fanmingming** [comment]
![image](https://github.com/fanmingming/live/assets/4993993/82fe030b-153a-4beb-ba39-f78767464ff8)

**Comment by BRUCEZHANG-dongming** [comment]
朋友们怎么取消订阅邮箱通知啊😅，怎么点了取消订阅没啥用。发自我的 iPhone在 2023年8月11日，10:40，范明明 ***@***.***> 写道：﻿

**Comment by 7890qwaszx** [comment]
流量问题可以考虑下cloudflare

**Comment by fanmingming** [comment]
源php文件构建在Vercel，都是动态内容，Cloudflare会增加访问延迟影响体验。现在已经升级Vercel套餐了。
