### ISSUE TITLE
不支持的音频/视频格式

### ISSUE THREAD

**Issue by kangyufeng219** [fanmingming/live#75]
## 遇到的问题	
今天大概是在10点以后播放时出现不支持的音频或者视频格式。

## 您使用的源
使用的Global源

## 有问题的频道名称
CCTV1 CCTV6 CCTV8

**Comment by fanmingming** [comment]
感谢反馈，应该是您播放器解码的问题。经过测试多款播放器都可以正常播放，建议使用其他播放器进行尝试。
