### ISSUE TITLE
有办法回看吗

### ISSUE THREAD

**Issue by xinxin2021** [fanmingming/live#78]
有IPv6，用的是Kodi，看见issues里有人回看，想问问怎么设置可以回看？

**Comment by xibeilang0616** [comment]
目前ipv6直播源没办法回看
不过fangmingming的另一个v6直播源每个台都可以回看：
![屏幕截图 2023-08-14 133546](https://github.com/fanmingming/live/assets/56585354/b6d25cd4-32cb-4a80-8fef-32779afc284e)
第一种方法：下载该直播源
第二种方法，不需要下载直播源，首先你懂技术会玩为前提，在直播app接口中把IP删除
![屏幕截图 2023-08-14 134508](https://github.com/fanmingming/live/assets/56585354/fc7b7087-c4b1-47c0-bbf4-9f038101e846)
不过v6直播源和ipv6直播源都是ipv6直播源，央视卫视一样，地方台有点差异

**Comment by xinxin2021** [comment]
> 目前ipv6直播源没办法回看 不过fanmingming的另一个v6直播源每个台都可以回看：
> 
> ![屏幕截图 2023-08-14 133546](https://user-images.githubusercontent.com/56585354/260366247-b6d25cd4-32cb-4a80-8fef-32779afc284e.png)
> 
> 第一种方法：下载该直播源(有的网络需要翻墙)
> 
> 第二种方法：不需要下载直播源，首先你懂技术会玩为前提，按照图片指示位置在直播app接口中粘贴复制时把IP 两个字母删除，就可以回看你想看的又错过的直播节目
> 
> 也可以在v6前面添加ip又回到你以前的IPv6直播源，切换不同的直播源玩
> 
> ![屏幕截图 2023-08-14 134508](https://user-images.githubusercontent.com/56585354/260367558-fc7b7087-c4b1-47c0-bbf4-9f038101e846.png)
> 
> 不过v6直播源和ipv6 专用直播源都是ipv6 性质的直播源，央视卫视都一样，地方台稍微有点差异

感谢感谢，已经解决了。
