### ISSUE TITLE
希望增加汕头综合、汕头文旅体育、汕头经济电视台，非常感谢

### ISSUE THREAD

**Issue by 25689056** [fanmingming/live#79]
## 遇到的问题	
请在此描述您遇到的问题。

## 您使用的源
如：IPv6、Global或Radio

## 有问题的频道名称
在此填写的频道名称。

**Comment by fanmingming** [comment]
抱歉，个人精力有限。只能尽力搞好目前已有的频道，尽量搞稳定一点。有稳定的源会持续保持更新，请继续关注后期维护。

**Comment by jshen0754** [comment]
很期待加入汕头的三个台，这个源是用过最好最稳定的。辛苦了！
