### ISSUE TITLE
IPTV-Checker-2.5-Simplified-Chinese软件闪退（crash）

### ISSUE THREAD

**Issue by tsjiang2017** [fanmingming/live#8]
复现方法：
1 打开软件
2 通过“打开m3u8”导入m3u8文件
3 1~2秒内按下右侧的向下按钮
4 m3u8列表内数据并滚动变化
5 软件crash

**Comment by fanmingming** [comment]
导入m3u文件后，软件会通过互联网加载m3u文件内置的电台或电视台logo，建议在加载完成后进行检测！

**Comment by tsjiang2017** [comment]
是这样的，就只是导入m3u文件，并未按下”检查“按钮。是否这个时候已经开始检查了所以造成crash情况？
