### ISSUE TITLE
绝大部分连接失效

### ISSUE THREAD

**Issue by minion1122** [fanmingming/live#80]
## 遇到的问题	
本人使用山东联通网络。昨天可以正常连接，但是今天开始除了**非大陆地区电视台**，中央1等以及地方电视台全部不能连接。望修复谢谢！

## 您使用的源
Global

## 有问题的频道名称
All

**Comment by fanmingming** [comment]
感谢反馈，ipv4比较容易失效。已紧急修复，希望能坚持久一点。
