### ISSUE TITLE
有个台的直播源有点问题

### ISSUE THREAD

**Issue by yk8899** [fanmingming/live#81]
那就是测试频道“儒释道经”这个直播源有疑问，您这个是m3u8后面是Key的，这个在这里没用，最好百度搜索华藏卫视网站获取直播源这样才是永久有效的我都是这样使用的。

        贡献台湾几个佛教有效的直播源用了很久了(自己使用的)
生命电视台,http://61.216.67.119:1935/lifetv/lifetv.stream/manifest.m3u8
生命电视台,http://61.216.67.119:1935/lifetv/lifetv.stream/manifest.m3u8
生命电视台,http://61.216.67.119:1935/lifetv/lifetv.stream/manifest.mpd
生命电视台,http://211.73.19.201/live/AB167E56-808C-81D4-6471-76DC400D5192.m3u8?fmt=x264_1200K_ts&cpid=admin&size=1920X1080
台湾唯心电视,http://mobile.ccdntech.com/transcoder/_definst_/vod164_Live/live/chunklist_w1177047531.m3u8
台湾唯心电视,https://mobile.ccdntech.com/transcoder/_definst_/vod164_Live/live/playlist.m3u8
台湾唯心电视,rtsp://mobile.ccdntech.com/transcoder/_definst_/vod164_Live/live_dms
台湾唯心电视,http://mobile.ccdntech.com/transcoder/_definst_/vod164_Live/live/chunklist_w1177047531.m3u8
台湾唯心电视,https://mobile.ccdntech.com/transcoder/_definst_/vod164_Live/live/playlist.m3u8
台湾唯心电视,http://211.73.19.201/live/549EA747-57A0-90EA-05EE-AE6169A8BEB7.m3u8?fmt=x264_1200K_ts&cpid=admin&size=1920X1080
台湾大爱一台,http://pulltv1.wanfudaluye.com/live/tv1.m3u8
台湾大爱二台,http://pulltv1.wanfudaluye.com/live/tv2.m3u8
华藏卫视（净空老法师）,http://js1.amtb.cn/liveedge/_definst_/livetv/playlist.m3u8
华藏卫视（净空老法师）,https://vod.amtb.de/liveedge/_definst_/smil:livetv.smil/chunklist_b428000.m3u8
华藏卫视（净空老法师）,https://tw3.amtb.de/liveedge/_definst_/smil:livetv.smil/chunklist_b828000.m3u8
华藏卫视（净空老法师）,https://js1.amtb.cn/liveedge/_definst_/smil:livetv.smil/chunklist_b828000.m3u8
华藏卫视（净空老法师）,https://de1.amtb.de/liveedge/_definst_/smil:livetv.smil/chunklist_w2021665399_b828000.m3u8
华藏卫视（净空老法师）,https://hk1.amtb.de/liveedge/_definst_/smil:livetv.smil/chunklist_w1631161688_b828000.m3u8
华藏卫视（净空老法师）,https://sg1.amtb.de/liveedge/_definst_/smil:livetv.smil/chunklist_w1071093527_b828000.m3u8
华藏卫视（净空老法师）,https://vod.amtb.de/redirect/liveedge/_definst_/smil:livetv.smil/playlist.m3u8
悟道法师,https://vod.amtb.de/liveedge/_definst_/wdmaster/chunklist.m3u8
悟道法师,https://tw4.amtb.de/liveedgehttp/_definst_/wdmaster/chunklist.m3u8
悟道法师,https://js1.amtb.cn/liveedge/_definst_/wdmaster/chunklist.m3u8
悟道法师,https://de1.amtb.de/liveedge/_definst_/wdmaster/playlist.m3u8
悟道法师,https://hk1.amtb.de/liveedge/_definst_/wdmaster/chunklist_w1591488665.m3u8
悟道法师,https://sg1.amtb.de/liveedge/_definst_/wdmaster/playlist.m3u8
悟道法师,https://vod.amtb.de/redirect/liveedge/_definst_/wdmaster/playlist.m3u8
多元文化,https://vod.amtb.de/liveedge/_definst_/education/chunklist.m3u8
多元文化,https://tw4.amtb.de/liveedgehttp/_definst_/education/chunklist.m3u8
多元文化,https://vod.amtb.de/liveedge/_definst_/education/chunklist.m3u8
多元文化,https://de1.amtb.de/liveedge/_definst_/education/playlist.m3u8
多元文化,https://hk1.amtb.de/liveedge/_definst_/education/chunklist_w1067577122.m3u8
多元文化,https://sg1.amtb.de/liveedge/_definst_/education/playlist.m3u8
多元文化,https://vod.amtb.de/redirect/liveedge/_definst_/education/playlist.m3u8
English,https://vod.amtb.de/redirect/liveedge/_definst_/English/playlist.m3u8
三時繫念法會,https://vod.amtb.de/liveedge/_definst_/smil:sanshi_720p.smil/chunklist_b828000.m3u8
三時繫念法會,https://tw3.amtb.de/liveedge/_definst_/smil:sanshi_720p.smil/chunklist_b828000.m3u8
三時繫念法會,https://de1.amtb.de/liveedge/_definst_/smil:sanshi_720p.smil/chunklist_w1197007899_b428000.m3u8
三時繫念法會,https://hk1.amtb.de/liveedge/_definst_/smil:sanshi_720p.smil/chunklist_w624672444_b828000.m3u8
三時繫念法會,https://sg1.amtb.de/liveedge/_definst_/smil:sanshi_720p.smil/chunklist_w156722507_b828000.m3u8
三時繫念法會,https://vod.amtb.de/redirect/liveedge/_definst_/smil:sanshi_720p.smil/playlist.m3u8
网络念佛堂,https://js1.amtb.cn/liveedge/_definst_/smil:amtb.smil/chunklist_b828000.m3u8
网络念佛堂,https://tw4.amtb.de/liveedgehttp/_definst_/smil:amtb.smil/chunklist_b828000.m3u8
网络念佛堂,https://de1.amtb.de/liveedge/_definst_/smil:amtb.smil/chunklist_w41969579_b428000.m3u8
网络念佛堂,https://hk1.amtb.de/liveedge/_definst_/smil:amtb.smil/chunklist_w1231453601_b828000.m3u8
网络念佛堂,https://sg1.amtb.de/liveedge/_definst_/smil:amtb.smil/chunklist_w1128537717_b428000.m3u8
网络念佛堂,https://vod.amtb.de/redirect/liveedge/_definst_/smil:amtb.smil/playlist.m3u8

**Comment by fanmingming** [comment]
感谢，等不忙更新上。
