### ISSUE TITLE
北京频道内容错误

### ISSUE THREAD

**Issue by ermiao** [fanmingming/live#84]
## 遇到的问题	
北京频道下的体育休闲，实际内容和纪实频道重复

## 您使用的源
IPv6/plus

## 有问题的频道名称
北京体育休闲

**Comment by fanmingming** [comment]
已经修复了，包括其中有两个河南频道不能播放的问题也已经解决。

**Comment by ermiao** [comment]
> 已经修复了，包括其中有两个河南频道不能播放的问题也已经解决。

大感谢！
