### ISSUE TITLE
请问一下为什么删除了无线新闻台的源呢？

### ISSUE THREAD

**Issue by rickyrick2002** [fanmingming/live#86]
比如原来的这个 http://sc2022.stream-link.org/tv2306.php?id=h04  ， 相关的香港的源好像在最近的commit删去了，为什么呢，试了是可以看的。

**Comment by fanmingming** [comment]
感谢，因为在直连的情况下无法播放所以删掉了。

**Comment by rickyrick2002** [comment]
哦原来是这样，可以在VLC里配置http proxy的，我是这样看的。
