### ISSUE TITLE
一个IPTV爱好者的小建议

### ISSUE THREAD

**Issue by tinygreet** [fanmingming/live#89]
## 意见建议
请在此提出您的意见或建议。
 先描述一下本人的设备和网络情况。。联通500M宽带，光猫桥接，openwrt拨号。购买的Apple TV，所以需要直播源。目前主要使用TV+ 和APTV这两款软件

建议1：增加epg的gz格式，因为TV+目前不支持xml的格式
建议2：增加缺失的台标，部分台标是没有的，比如CCTV8K
建议3：部分epg有错误，比如浙江卫视，我打开软件的节目列表和实际的不同。。

另外，我也乐意分享tv logo，感谢你的工作

**Comment by tinygreet** [comment]
![Snipaste_2023-08-26_17-20-00](https://github.com/fanmingming/live/assets/23146020/5a6d6930-00d4-4701-8781-5820da7f0f3a)



比如这个求索生活的epg节目单，是明显错误的。


有些节目  epg节目单还没有收录，比如 探索纪实，lovenature（爱自然），北京纪实8k，爱上4K，苏州4k

**Comment by fanmingming** [comment]
感谢您的反馈，目前项目的EPG为112114内容分发，每小时自动更新构建的。
EPG显示错误的相关问题您可以提交至 https://www.112114.xyz/epg%E9%97%AE%E9%A2%98%E5%8F%8D%E9%A6%88/
