### ISSUE TITLE
增加一个cctv8k logo

### ISSUE THREAD

**Issue by tinygreet** [fanmingming/live#90]
因为没有上传权限，所以发在这里
https://gitee.com/Black_crow/epglogo/blob/master/cctv/CCTV8k.png

另外，这个仓库有一些其他的logo，可以使用
https://gitee.com/Black_crow/epglogo/tree/master/

**Comment by fanmingming** [comment]
感谢，明天传好。

**Comment by fanmingming** [comment]
已经传好了路径在 https://live.fanmingming.com/tv/CCTV8K.png
