### ISSUE TITLE
网络似乎不稳定

### ISSUE THREAD

**Issue by klcb2010** [fanmingming/live#91]
测试了手机端和电脑端，都有加载为0kb的状况  ，以为是DNS问题，结果测试好几遍确认是资源问题。卡的时候任何台都卡

![截屏图片 (1)](https://github.com/fanmingming/live/assets/32628414/486288a0-c540-4748-a50e-3dced6fd5dd6)
![截屏图片](https://github.com/fanmingming/live/assets/32628414/39a255da-187e-4b8c-83f7-d7bdbacd4ddb)

**Comment by fanmingming** [comment]
感谢反馈，已经注意到出现的中断问题，似乎是Vercel网络波动问题造成的。还在找具体原因排查。😓

**Comment by fanmingming** [comment]
晚间高峰期测试了一个半小时没有出现播放问题，后面有问题欢迎继续提出。
如出现频繁缓冲的情况，一般是请求量大源服务器流量压力较大。
