### ISSUE TITLE
用播放器播放不了，提示CORS错误

### ISSUE THREAD

**Issue by paxdiamon** [fanmingming/live#94]
## 遇到的问题	
用播放器播放不了，提示CORS错误
https://live.fanmingming.com/player/?vurl=https://cntv.sbs/tv?auth=230830&id=cctv1

Access to XMLHttpRequest at 'https://cntv.sbs/tv?auth=230830&id=cctv1' from origin 'https://live.fanmingming.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

## 您使用的源
Global

## 有问题的频道名称
所有&id=

像这种 https://cntv.sbs/tv?auth=230830&id=cctv1 后面不是.m3u8结尾的，如何使用Dplayer播放？

**Comment by zjcnew** [comment]
跨越这种问题，Web端播放可以采用反向代理的方式解决。

    server {
        listen       80;
        server_name  localhost;
        
        location ^~/cctv/ {
            proxy_pass https://cntv.sbs/;
        }
    }
