### ISSUE TITLE
需要多大的带宽才能看

### ISSUE THREAD

**Issue by Botti307** [fanmingming/live#97]
## 遇到的问题
国内的大部分可以，偶尔卡一下，还是流畅的。但是我看韩国的每秒一卡，看不了。是广州100M电信宽带，是需要千兆宽带才行吗？
## 您使用的源
Global直播源
## 有问题的频道名称
韩国KBS、SBS、MBC等

**Comment by fanmingming** [comment]
感谢反馈，韩国的频道源都在测试组。国内网络高峰期观看是会出现卡顿，属于正常情况。观看4K频道直播一般35Mbps下行就满足流畅观看了。所以，100Mbps观看直播节目卡顿的话一般是源的问题。
