### ISSUE TITLE
关于源的变更

### ISSUE THREAD

**Issue by bear0328** [fanmingming/live#98]
## 意见建议
1.昨天发现不能看直播了,有语音提示,并且有链接给到,提示更新,非常棒的一个提示,就是是否可以有更好的方式可以自动更新,家里老人看的时候,我帮忙更新时效性没有这么快.
2.IPV6的话,是不是需要我家里的全套设备包括终端,都需要支持IPV6?

感谢!

**Comment by fanmingming** [comment]
感谢提问，IPv6一般运营商都会默认下发。如果你是路由器拨号上网，需要路由器支持IPv6功能，目前市面上在售的理由设备都可以开启IPv6。你可以先检查下自己的网络是否有IPv6接入，测试网址https://www.test-ipv6.com/index.html.zh_CN 如果具备IPv6建议使用IPv6源观看节目（IPv6源的节目不失效不会频繁变更和更新）。目前由于IPv4源被各种商用收费的形式内置到各种tvbox软件，为杜绝这种情况只能不定期变更auth参数来应对。

**Comment by door-not** [comment]
请教一下 9.8号更新后 tivimate无法播放 一直提示更新 包括Ipv6的 都不行  不清楚更新了什么 是没有具体测试吗 还是说跟新auth参数后导致tivimate2.8版本过旧 需要更换其他的播放器

**Comment by door-not** [comment]
抱歉 反馈的问题是软件导致的问题  重新添加就好了  tivimate2.80可能存在bug  必须手动添加 自动添加的可能因为cookie原因 导致更新不好用  播放软件的bug

**Comment by fanmingming** [comment]
> 请教一下 9.8号更新后 tivimate无法播放 一直提示更新 包括Ipv6的 都不行 不清楚更新了什么 是没有具体测试吗 还是说跟新auth参数后导致tivimate2.8版本过旧 需要更换其他的播放器

应该是破解版软件的问题，正版测试过可以正常播放。
