### ISSUE TITLE
切换到没有链接的台会卡死

### ISSUE THREAD

**Issue by balala2oo8** [fanmingming/live#99]
源：Global 中间有几个台没有地址，如：凤凰香港。使用影视仓5.0.7切换到这个台就会卡死退出，重新进入直播也是直接卡死退出，如果app设置的是默认进入直播，会导致打开软件就卡死了。虽然这是软件的问题，但还是希望把空链接替换一下。

港澳,#genre#
凤凰中文,https://cntv.sbs/tv/cbn.php?id=xfjcHD
凤凰资讯,
凤凰香港,
翡翠台,https://pi.0472.org/tv/fct.php?auth=2309081833
明珠台,https://pi.0472.org/tv/mzt.php?auth=2309081833
澳视澳门,https://pi.0472.org/tv/asam.php?auth=2309081833
澳亚卫视,https://pi.0472.org/tv/aoya.php?auth=2309081833
香港卫视,http://zhibo.hkstv.tv/livestream/mutfysrq/playlist.m3u8
RTHK32,https://rthktv32-live.akamaized.net/hls/live/2036819/RTHKTV32/stream2/streamPlaylist.m3u8
J2台,
莲花卫视,https://cntv.sbs/tv/lhws.php
无线新闻台,
无线财经台,
NOW新闻台,
香港国际财经台,
RTHK31,

**Comment by fanmingming** [comment]
感谢提问。有些频道切换以后需要跳转，等待跳转播放地址以后即可正常观看节目。留空的的频道是为了方便更新较为常见的一些频道更方便。下次更新会注意这个问题。

**Comment by balala2oo8** [comment]
谢谢！
